**TUGAS ORYZA AYUNDA PUTRI**

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/data.csv')
df

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,Bodycare abis sabun + lotion sekalian beli 2 g...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN
1,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo Beli 2 Gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN
2,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN
3,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k !! Diskon beli di link ini https://t.co/r...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN
4,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,@LazadaID Di Lazada Ramadan Pesta Gajian aku p...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN
5,2026185230848286951,Tue Feb 24 08:18:01 +0000 2026,0,@saphelune_ udh gitu selesainya masih harus sk...,2026209992148488500,NaN,saphelune_,in,NaN,0,1,0,https://x.com/undefined/status/202620999214848...,1353536078687342594,NaN
6,2026207726976872844,Tue Feb 24 08:09:05 +0000 2026,3,￼Ciara Scar Set aku tuh punya kulit yang sens...,2026207740239249649,https://pbs.twimg.com/media/HB6JMmhaUAA73w9.jpg,irapersa,in,NaN,0,1,1,https://x.com/undefined/status/202620774023924...,1022437026719657984,NaN
7,2026207726976872844,Tue Feb 24 08:09:01 +0000 2026,796,BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...,2026207726976872844,https://pbs.twimg.com/media/HB6JL2JbYAEjPPE.jpg,NaN,in,NaN,1,19,157,https://x.com/undefined/status/202620772697687...,1022437026719657984,NaN
8,2026119699835322640,Tue Feb 24 07:53:57 +0000 2026,0,@potarisweatt apalg pas bagian bodycare butuh ...,2026203935552500091,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202620393555250...,1336009723468869635,NaN
9,2026176027517661268,Tue Feb 24 06:03:14 +0000 2026,0,aku suka bgt jalan-jalan ke alam!! resikonya b...,2026176070509363282,https://pbs.twimg.com/media/HB5sXqQaIAAxRmW.jpg,terangremboelan,in,NaN,0,1,0,https://x.com/undefined/status/202617607050936...,1667470100914634752,NaN
10,2026144267899695257,Tue Feb 24 04:03:39 +0000 2026,0,@stberryorange @drwhiteskincare Pas banget bod...,2026145978856980659,NaN,stberryorange,in,NaN,0,1,0,https://x.com/undefined/status/202614597885698...,709063820233146368,NaN
11,2026141939331146014,Tue Feb 24 03:47:36 +0000 2026,0,-selldips skincare bodycare parfum baju tankto...,2026141939331146014,https://pbs.twimg.com/media/HB5NVWGbUAAcnZS.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202614193933114...,1847520733028896769,NaN
12,2026132112374702508,Tue Feb 24 03:08:33 +0000 2026,0,Oh My Skin ! PINK LOVE GLUTA SOAP sabun pencer...,2026132112374702508,https://pbs.twimg.com/media/HB5EafrasAAaHZ7.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202613211237470...,1484895347315187712,NaN
13,2026119699835322640,Tue Feb 24 02:29:36 +0000 2026,0,@potarisweatt tapi kalau pakai skincare bodyca...,2026122309690622438,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202612230969062...,1406251828417761282,NaN
14,2026119699835322640,Tue Feb 24 02:19:14 +0000 2026,28,baru sadar klo jd cewe tuh capek pliss. kudu r...,2026119699835322640,NaN,NaN,in,NaN,2,25,0,https://x.com/undefined/status/202611969983532...,2332802611,NaN
15,2025907789697298671,Tue Feb 24 02:02:02 +0000 2026,0,NAH cipa juga masukin L occitane sama Kerastas...,2026115369128370284,https://pbs.twimg.com/media/HB41LUtaYAAOijF.jpg,journeywithApr,in,NaN,0,0,0,https://x.com/undefined/status/202611536912837...,2402369514,NaN
16,2026112464983904497,Tue Feb 24 02:01:29 +0000 2026,0,@BosRQ_ skincare dan bodycare udah sekarat unt...,2026115232679313485,NaN,BosRQ_,in,NaN,0,0,0,https://x.com/undefined/status/202611523267931...,1926789679707238400,NaN
17,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,Bodycare abis sabun + lotion sekalian beli 2 g...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN
18,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo Beli 2 Gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN
19,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN
20,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k !! Diskon beli di link ini https://t.co/r...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN
21,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,@LazadaID Di Lazada Ramadan Pesta Gajian aku p...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN
22,2026185230848286951,Tue Feb 24 08:18:01 +0000 2026,0,@saphelune_ udh gitu selesainya masih harus sk...,2026209992148488500,NaN,saphelune_,in,NaN,0,1,0,https://x.com/undefined/status/202620999214848...,1353536078687342594,NaN
23,2026207726976872844,Tue Feb 24 08:09:05 +0000 2026,3,￼Ciara Scar Set aku tuh punya kulit yang sens...,2026207740239249649,https://pbs.twimg.com/media/HB6JMmhaUAA73w9.jpg,irapersa,in,NaN,0,1,1,https://x.com/undefined/status/202620774023924...,1022437026719657984,NaN
24,2026207726976872844,Tue Feb 24 08:09:01 +0000 2026,796,BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...,2026207726976872844,https://pbs.twimg.com/media/HB6JL2JbYAEjPPE.jpg,NaN,in,NaN,1,19,157,https://x.com/undefined/status/202620772697687...,1022437026719657984,NaN
25,2026119699835322640,Tue Feb 24 07:53:57 +0000 2026,0,@potarisweatt apalg pas bagian bodycare butuh ...,2026203935552500091,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202620393555250...,1336009723468869635,NaN
26,2026176027517661268,Tue Feb 24 06:03:14 +0000 2026,0,aku suka bgt jalan-jalan ke alam!! resikonya b...,2026176070509363282,https://pbs.twimg.com/media/HB5sXqQaIAAxRmW.jpg,terangremboelan,in,NaN,0,1,0,https://x.com/undefined/status/202617607050936...,1667470100914634752,NaN
27,2026144267899695257,Tue Feb 24 04:03:39 +0000 2026,0,@stberryorange @drwhiteskincare Pas banget bod...,2026145978856980659,NaN,stberryorange,in,NaN,0,1,0,https://x.com/undefined/status/202614597885698...,709063820233146368,NaN
28,2026141939331146014,Tue Feb 24 03:47:36 +0000 2026,0,-selldips skincare bodycare parfum baju tankto...,2026141939331146014,https://pbs.twimg.com/media/HB5NVWGbUAAcnZS.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202614193933114...,1847520733028896769,NaN
29,2026132112374702508,Tue Feb 24 03:08:33 +0000 2026,0,Oh My Skin ! PINK LOVE GLUTA SOAP sabun pencer...,2026132112374702508,https://pbs.twimg.com/media/HB5EafrasAAaHZ7.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202613211237470...,1484895347315187712,NaN
30,2026119699835322640,Tue Feb 24 02:29:36 +0000 2026,0,@potarisweatt tapi kalau pakai skincare bodyca...,2026122309690622438,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202612230969062...,1406251828417761282,NaN
31,2026119699835322640,Tue Feb 24 02:19:14 +0000 2026,28,baru sadar klo jd cewe tuh capek pliss. kudu r...,2026119699835322640,NaN,NaN,in,NaN,2,25,0,https://x.com/undefined/status/202611969983532...,2332802611,NaN
32,2025907789697298671,Tue Feb 24 02:02:02 +0000 2026,0,NAH cipa juga masukin L occitane sama Kerastas...,2026115369128370284,https://pbs.twimg.com/media/HB41LUtaYAAOijF.jpg,journeywithApr,in,NaN,0,0,0,https://x.com/undefined/status/202611536912837...,2402369514,NaN
33,2026112464983904497,Tue Feb 24 02:01:29 +0000 2026,0,@BosRQ_ skincare dan bodycare udah sekarat unt...,2026115232679313485,NaN,BosRQ_,in,NaN,0,0,0,https://x.com/undefined/status/202611523267931...,1926789679707238400,NaN
34,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,Bodycare abis sabun + lotion sekalian beli 2 g...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN
35,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo Beli 2 Gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN
36,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN
37,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k !! Diskon beli di link ini https://t.co/r...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN
38,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,@LazadaID Di Lazada Ramadan Pesta Gajian aku p...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN
39,2026185230848286951,Tue Feb 24 08:18:01 +0000 2026,0,@saphelune_ udh gitu selesainya masih harus sk...,2026209992148488500,NaN,saphelune_,in,NaN,0,1,0,https://x.com/undefined/status/202620999214848...,1353536078687342594,NaN
40,2026207726976872844,Tue Feb 24 08:09:05 +0000 2026,3,￼Ciara Scar Set aku tuh punya kulit yang sens...,2026207740239249649,https://pbs.twimg.com/media/HB6JMmhaUAA73w9.jpg,irapersa,in,NaN,0,1,1,https://x.com/undefined/status/202620774023924...,1022437026719657984,NaN
41,2026207726976872844,Tue Feb 24 08:09:01 +0000 2026,796,BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...,2026207726976872844,https://pbs.twimg.com/media/HB6JL2JbYAEjPPE.jpg,NaN,in,NaN,1,19,157,https://x.com/undefined/status/202620772697687...,1022437026719657984,NaN
42,2026119699835322640,Tue Feb 24 07:53:57 +0000 2026,0,@potarisweatt apalg pas bagian bodycare butuh ...,2026203935552500091,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202620393555250...,1336009723468869635,NaN
43,2026176027517661268,Tue Feb 24 06:03:14 +0000 2026,0,aku suka bgt jalan-jalan ke alam!! resikonya b...,2026176070509363282,https://pbs.twimg.com/media/HB5sXqQaIAAxRmW.jpg,terangremboelan,in,NaN,0,1,0,https://x.com/undefined/status/202617607050936...,1667470100914634752,NaN
44,2026144267899695257,Tue Feb 24 04:03:39 +0000 2026,0,@stberryorange @drwhiteskincare Pas banget bod...,2026145978856980659,NaN,stberryorange,in,NaN,0,1,0,https://x.com/undefined/status/202614597885698...,709063820233146368,NaN
45,2026141939331146014,Tue Feb 24 03:47:36 +0000 2026,0,-selldips skincare bodycare parfum baju tankto...,2026141939331146014,https://pbs.twimg.com/media/HB5NVWGbUAAcnZS.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202614193933114...,1847520733028896769,NaN
46,2026132112374702508,Tue Feb 24 03:08:33 +0000 2026,0,Oh My Skin ! PINK LOVE GLUTA SOAP sabun pencer...,2026132112374702508,https://pbs.twimg.com/media/HB5EafrasAAaHZ7.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202613211237470...,1484895347315187712,NaN
47,2026119699835322640,Tue Feb 24 02:29:36 +0000 2026,0,@potarisweatt tapi kalau pakai skincare bodyca...,2026122309690622438,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202612230969062...,1406251828417761282,NaN
48,2026119699835322640,Tue Feb 24 02:19:14 +0000 2026,28,baru sadar klo jd cewe tuh capek pliss. kudu r...,2026119699835322640,NaN,NaN,in,NaN,2,25,0,https://x.com/undefined/status/202611969983532...,2332802611,NaN
49,2025907789697298671,Tue Feb 24 02:02:02 +0000 2026,0,NAH cipa juga masukin L occitane sama Kerastas...,2026115369128370284,https://pbs.twimg.com/media/HB41LUtaYAAOijF.jpg,journeywithApr,in,NaN,0,0,0,https://x.com/undefined/status/202611536912837...,2402369514,NaN
50,2026112464983904497,Tue Feb 24 02:01:29 +0000 2026,0,@BosRQ_ skincare dan bodycare udah sekarat unt...,2026115232679313485,NaN,BosRQ_,in,NaN,0,0,0,https://x.com/undefined/status/202611523267931...,1926789679707238400,NaN

In [4]:
#copy data
df_copy = df.copy()
df_copy.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,Bodycare abis sabun + lotion sekalian beli 2 g...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN
1,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo Beli 2 Gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN
2,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN
3,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k !! Diskon beli di link ini https://t.co/r...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN
4,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,@LazadaID Di Lazada Ramadan Pesta Gajian aku p...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN

In [8]:

#ubah data menjadi huruf kecil
df_copy['full_text'] = df_copy['full_text'].str.lower()
df_copy.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,bodycare abis sabun + lotion sekalian beli 2 g...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN
1,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo beli 2 gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN
2,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN
3,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k !! diskon beli di link ini https://t.co/r...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN
4,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,@lazadaid di lazada ramadan pesta gajian aku p...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN

In [ ]:
#buka baris full_texnya saja
df_copy['full_text']

0     bodycare abis sabun + lotion sekalian beli 2 g...
1     siapa sih yang bisa nolak promo beli 2 gratis ...
2     skincare sama bodycare udah masuk wishlist tin...
3     225k !! diskon beli di link ini https://t.co/r...
4     @lazadaid di lazada ramadan pesta gajian aku p...
5     @saphelune_ udh gitu selesainya masih harus sk...
6      ￼ciara scar set aku tuh punya kulit yang sens...
7     beberapa combo bodycare yang paling gong 2026 ...
8     @potarisweatt apalg pas bagian bodycare butuh ...
9     aku suka bgt jalan-jalan ke alam!! resikonya b...
10    @stberryorange @drwhiteskincare pas banget bod...
11    -selldips skincare bodycare parfum baju tankto...
12    oh my skin ! pink love gluta soap sabun pencer...
13    @potarisweatt tapi kalau pakai skincare bodyca...
14    baru sadar klo jd cewe tuh capek pliss. kudu r...
15    nah cipa juga masukin l occitane sama kerastas...
16    @bosrq_ skincare dan bodycare udah sekarat unt...
17    bodycare abis sabun + lotion sekalian beli 2 g...
18    siapa sih yang bisa nolak promo beli 2 gratis ...
19    skincare sama bodycare udah masuk wishlist tin...
20    225k !! diskon beli di link ini https://t.co/r...
21    @lazadaid di lazada ramadan pesta gajian aku p...
22    @saphelune_ udh gitu selesainya masih harus sk...
23     ￼ciara scar set aku tuh punya kulit yang sens...
24    beberapa combo bodycare yang paling gong 2026 ...
25    @potarisweatt apalg pas bagian bodycare butuh ...
26    aku suka bgt jalan-jalan ke alam!! resikonya b...
27    @stberryorange @drwhiteskincare pas banget bod...
28    -selldips skincare bodycare parfum baju tankto...
29    oh my skin ! pink love gluta soap sabun pencer...
30    @potarisweatt tapi kalau pakai skincare bodyca...
31    baru sadar klo jd cewe tuh capek pliss. kudu r...
32    nah cipa juga masukin l occitane sama kerastas...
33    @bosrq_ skincare dan bodycare udah sekarat unt...
34    bodycare abis sabun + lotion sekalian beli 2 g...
35    siapa sih yang bisa nolak promo beli 2 gratis ...
36    skincare sama bodycare udah masuk wishlist tin...
37    225k !! diskon beli di link ini https://t.co/r...
38    @lazadaid di lazada ramadan pesta gajian aku p...
39    @saphelune_ udh gitu selesainya masih harus sk...
40     ￼ciara scar set aku tuh punya kulit yang sens...
41    beberapa combo bodycare yang paling gong 2026 ...
42    @potarisweatt apalg pas bagian bodycare butuh ...
43    aku suka bgt jalan-jalan ke alam!! resikonya b...
44    @stberryorange @drwhiteskincare pas banget bod...
45    -selldips skincare bodycare parfum baju tankto...
46    oh my skin ! pink love gluta soap sabun pencer...
47    @potarisweatt tapi kalau pakai skincare bodyca...
48    baru sadar klo jd cewe tuh capek pliss. kudu r...
49    nah cipa juga masukin l occitane sama kerastas...
50    @bosrq_ skincare dan bodycare udah sekarat unt...
Name: full_text, dtype: object

In [ ]:
#hilangkan tanda baca
df_copy['full_text'] = df_copy['full_text'].str.replace('[^\w\s]','',regex=True)
df_copy['full_text']

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_34152\2155907621.py:1: SyntaxWarning: invalid escape sequence '\w'
  df_copy['full_text'] = df_copy['full_text'].str.replace('[^\w\s]','',regex=True)

0     bodycare abis sabun  lotion sekalian beli 2 gr...
1     siapa sih yang bisa nolak promo beli 2 gratis ...
2     skincare sama bodycare udah masuk wishlist tin...
3     225k  diskon beli di link ini httpstcoriprfe7a...
4     lazadaid di lazada ramadan pesta gajian aku pe...
5     saphelune_ udh gitu selesainya masih harus ski...
6      ciara scar set aku tuh punya kulit yang sensi...
7     beberapa combo bodycare yang paling gong 2026 ...
8     potarisweatt apalg pas bagian bodycare butuh w...
9     aku suka bgt jalanjalan ke alam resikonya bawa...
10    stberryorange drwhiteskincare pas banget bodyc...
11    selldips skincare bodycare parfum baju tanktop...
12    oh my skin  pink love gluta soap sabun pencera...
13    potarisweatt tapi kalau pakai skincare bodycar...
14    baru sadar klo jd cewe tuh capek pliss kudu ra...
15    nah cipa juga masukin l occitane sama kerastas...
16    bosrq_ skincare dan bodycare udah sekarat untu...
17    bodycare abis sabun  lotion sekalian beli 2 gr...
18    siapa sih yang bisa nolak promo beli 2 gratis ...
19    skincare sama bodycare udah masuk wishlist tin...
20    225k  diskon beli di link ini httpstcoriprfe7a...
21    lazadaid di lazada ramadan pesta gajian aku pe...
22    saphelune_ udh gitu selesainya masih harus ski...
23     ciara scar set aku tuh punya kulit yang sensi...
24    beberapa combo bodycare yang paling gong 2026 ...
25    potarisweatt apalg pas bagian bodycare butuh w...
26    aku suka bgt jalanjalan ke alam resikonya bawa...
27    stberryorange drwhiteskincare pas banget bodyc...
28    selldips skincare bodycare parfum baju tanktop...
29    oh my skin  pink love gluta soap sabun pencera...
30    potarisweatt tapi kalau pakai skincare bodycar...
31    baru sadar klo jd cewe tuh capek pliss kudu ra...
32    nah cipa juga masukin l occitane sama kerastas...
33    bosrq_ skincare dan bodycare udah sekarat untu...
34    bodycare abis sabun  lotion sekalian beli 2 gr...
35    siapa sih yang bisa nolak promo beli 2 gratis ...
36    skincare sama bodycare udah masuk wishlist tin...
37    225k  diskon beli di link ini httpstcoriprfe7a...
38    lazadaid di lazada ramadan pesta gajian aku pe...
39    saphelune_ udh gitu selesainya masih harus ski...
40     ciara scar set aku tuh punya kulit yang sensi...
41    beberapa combo bodycare yang paling gong 2026 ...
42    potarisweatt apalg pas bagian bodycare butuh w...
43    aku suka bgt jalanjalan ke alam resikonya bawa...
44    stberryorange drwhiteskincare pas banget bodyc...
45    selldips skincare bodycare parfum baju tanktop...
46    oh my skin  pink love gluta soap sabun pencera...
47    potarisweatt tapi kalau pakai skincare bodycar...
48    baru sadar klo jd cewe tuh capek pliss kudu ra...
49    nah cipa juga masukin l occitane sama kerastas...
50    bosrq_ skincare dan bodycare udah sekarat untu...
Name: full_text, dtype: object

In [15]:
#hilangkan karakter yang berulang lebih dari 2 kali
df_copy['full_text'] = df_copy['full_text'].str.replace(r'(.)\1{2,}', r'\1',regex=True)
df_copy['full_text']

0     bodycare abis sabun  lotion sekalian beli 2 gr...
1     siapa sih yang bisa nolak promo beli 2 gratis ...
2     skincare sama bodycare udah masuk wishlist tin...
3     225k  diskon beli di link ini httpstcoriprfe7a...
4     lazadaid di lazada ramadan pesta gajian aku pe...
5     saphelune_ udh gitu selesainya masih harus ski...
6      ciara scar set aku tuh punya kulit yang sensi...
7     beberapa combo bodycare yang paling gong 2026 ...
8     potarisweatt apalg pas bagian bodycare butuh w...
9     aku suka bgt jalanjalan ke alam resikonya bawa...
10    stberryorange drwhiteskincare pas banget bodyc...
11    selldips skincare bodycare parfum baju tanktop...
12    oh my skin  pink love gluta soap sabun pencera...
13    potarisweatt tapi kalau pakai skincare bodycar...
14    baru sadar klo jd cewe tuh capek pliss kudu ra...
15    nah cipa juga masukin l occitane sama kerastas...
16    bosrq_ skincare dan bodycare udah sekarat untu...
17    bodycare abis sabun  lotion sekalian beli 2 gr...
18    siapa sih yang bisa nolak promo beli 2 gratis ...
19    skincare sama bodycare udah masuk wishlist tin...
20    225k  diskon beli di link ini httpstcoriprfe7a...
21    lazadaid di lazada ramadan pesta gajian aku pe...
22    saphelune_ udh gitu selesainya masih harus ski...
23     ciara scar set aku tuh punya kulit yang sensi...
24    beberapa combo bodycare yang paling gong 2026 ...
25    potarisweatt apalg pas bagian bodycare butuh w...
26    aku suka bgt jalanjalan ke alam resikonya bawa...
27    stberryorange drwhiteskincare pas banget bodyc...
28    selldips skincare bodycare parfum baju tanktop...
29    oh my skin  pink love gluta soap sabun pencera...
30    potarisweatt tapi kalau pakai skincare bodycar...
31    baru sadar klo jd cewe tuh capek pliss kudu ra...
32    nah cipa juga masukin l occitane sama kerastas...
33    bosrq_ skincare dan bodycare udah sekarat untu...
34    bodycare abis sabun  lotion sekalian beli 2 gr...
35    siapa sih yang bisa nolak promo beli 2 gratis ...
36    skincare sama bodycare udah masuk wishlist tin...
37    225k  diskon beli di link ini httpstcoriprfe7a...
38    lazadaid di lazada ramadan pesta gajian aku pe...
39    saphelune_ udh gitu selesainya masih harus ski...
40     ciara scar set aku tuh punya kulit yang sensi...
41    beberapa combo bodycare yang paling gong 2026 ...
42    potarisweatt apalg pas bagian bodycare butuh w...
43    aku suka bgt jalanjalan ke alam resikonya bawa...
44    stberryorange drwhiteskincare pas banget bodyc...
45    selldips skincare bodycare parfum baju tanktop...
46    oh my skin  pink love gluta soap sabun pencera...
47    potarisweatt tapi kalau pakai skincare bodycar...
48    baru sadar klo jd cewe tuh capek pliss kudu ra...
49    nah cipa juga masukin l occitane sama kerastas...
50    bosrq_ skincare dan bodycare udah sekarat untu...
Name: full_text, dtype: object

In [17]:
#hilangkan spasi di awal dan akhir kalimat
df_copy['full_text'] = df_copy['full_text'].str.strip()
df_copy['full_text']

0     bodycare abis sabun  lotion sekalian beli 2 gr...
1     siapa sih yang bisa nolak promo beli 2 gratis ...
2     skincare sama bodycare udah masuk wishlist tin...
3     225k  diskon beli di link ini httpstcoriprfe7a...
4     lazadaid di lazada ramadan pesta gajian aku pe...
5     saphelune_ udh gitu selesainya masih harus ski...
6     ciara scar set aku tuh punya kulit yang sensit...
7     beberapa combo bodycare yang paling gong 2026 ...
8     potarisweatt apalg pas bagian bodycare butuh w...
9     aku suka bgt jalanjalan ke alam resikonya bawa...
10    stberryorange drwhiteskincare pas banget bodyc...
11    selldips skincare bodycare parfum baju tanktop...
12    oh my skin  pink love gluta soap sabun pencera...
13    potarisweatt tapi kalau pakai skincare bodycar...
14    baru sadar klo jd cewe tuh capek pliss kudu ra...
15    nah cipa juga masukin l occitane sama kerastas...
16    bosrq_ skincare dan bodycare udah sekarat untu...
17    bodycare abis sabun  lotion sekalian beli 2 gr...
18    siapa sih yang bisa nolak promo beli 2 gratis ...
19    skincare sama bodycare udah masuk wishlist tin...
20    225k  diskon beli di link ini httpstcoriprfe7a...
21    lazadaid di lazada ramadan pesta gajian aku pe...
22    saphelune_ udh gitu selesainya masih harus ski...
23    ciara scar set aku tuh punya kulit yang sensit...
24    beberapa combo bodycare yang paling gong 2026 ...
25    potarisweatt apalg pas bagian bodycare butuh w...
26    aku suka bgt jalanjalan ke alam resikonya bawa...
27    stberryorange drwhiteskincare pas banget bodyc...
28    selldips skincare bodycare parfum baju tanktop...
29    oh my skin  pink love gluta soap sabun pencera...
30    potarisweatt tapi kalau pakai skincare bodycar...
31    baru sadar klo jd cewe tuh capek pliss kudu ra...
32    nah cipa juga masukin l occitane sama kerastas...
33    bosrq_ skincare dan bodycare udah sekarat untu...
34    bodycare abis sabun  lotion sekalian beli 2 gr...
35    siapa sih yang bisa nolak promo beli 2 gratis ...
36    skincare sama bodycare udah masuk wishlist tin...
37    225k  diskon beli di link ini httpstcoriprfe7a...
38    lazadaid di lazada ramadan pesta gajian aku pe...
39    saphelune_ udh gitu selesainya masih harus ski...
40    ciara scar set aku tuh punya kulit yang sensit...
41    beberapa combo bodycare yang paling gong 2026 ...
42    potarisweatt apalg pas bagian bodycare butuh w...
43    aku suka bgt jalanjalan ke alam resikonya bawa...
44    stberryorange drwhiteskincare pas banget bodyc...
45    selldips skincare bodycare parfum baju tanktop...
46    oh my skin  pink love gluta soap sabun pencera...
47    potarisweatt tapi kalau pakai skincare bodycar...
48    baru sadar klo jd cewe tuh capek pliss kudu ra...
49    nah cipa juga masukin l occitane sama kerastas...
50    bosrq_ skincare dan bodycare udah sekarat untu...
Name: full_text, dtype: object

In [19]:
#fungsi untuk membersihkan data full_text
def clean_full_text(df, column_name):

    df['full_text_clean'] = df[column_name].str.lower()

    df['full_text_clean'] = df['full_text_clean'].str.strip()

    df['full_text_clean'] = df['full_text_clean'].str.replace('[^\w\s]', '', regex=True)

    df['full_text_clean'] = df['full_text_clean'].str.replace(r'(.)\1{2,}', r'\1', regex=True)

    return df

<>:8: SyntaxWarning: invalid escape sequence '\w'
<>:8: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_34152\604652011.py:8: SyntaxWarning: invalid escape sequence '\w'
  df['full_text_clean'] = df['full_text_clean'].str.replace('[^\w\s]', '', regex=True)

In [20]:
# Jalankan fungsi
df = clean_full_text(df, 'full_text')

print(df[['full_text', 'full_text_clean']])

                                            full_text  \
0   Bodycare abis sabun  lotion sekalian beli 2 gr...
1   siapa sih yang bisa nolak promo Beli 2 Gratis ...
2   skincare sama bodycare udah masuk wishlist tin...
3   225k  Diskon beli di link ini httpstcoripRFe7A...
4   LazadaID Di Lazada Ramadan Pesta Gajian aku pe...
5   saphelune_ udh gitu selesainya masih harus ski...
6    Ciara Scar Set aku tuh punya kulit yang sensi...
7   BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...
8   potarisweatt apalg pas bagian bodycare butuh w...
9   aku suka bgt jalanjalan ke alam resikonya bawa...
10  stberryorange drwhiteskincare Pas banget bodyc...
11  selldips skincare bodycare parfum baju tanktop...
12  Oh My Skin  PINK LOVE GLUTA SOAP sabun pencera...
13  potarisweatt tapi kalau pakai skincare bodycar...
14  baru sadar klo jd cewe tuh capek pliss kudu ra...
15  NAH cipa juga masukin L occitane sama Kerastas...
16  BosRQ_ skincare dan bodycare udah sekarat untu...
17  Bodycare abis sabun  lotion sekalian beli 2 gr...
18  siapa sih yang bisa nolak promo Beli 2 Gratis ...
19  skincare sama bodycare udah masuk wishlist tin...
20  225k  Diskon beli di link ini httpstcoripRFe7A...
21  LazadaID Di Lazada Ramadan Pesta Gajian aku pe...
22  saphelune_ udh gitu selesainya masih harus ski...
23   Ciara Scar Set aku tuh punya kulit yang sensi...
24  BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...
25  potarisweatt apalg pas bagian bodycare butuh w...
26  aku suka bgt jalanjalan ke alam resikonya bawa...
27  stberryorange drwhiteskincare Pas banget bodyc...
28  selldips skincare bodycare parfum baju tanktop...
29  Oh My Skin  PINK LOVE GLUTA SOAP sabun pencera...
30  potarisweatt tapi kalau pakai skincare bodycar...
31  baru sadar klo jd cewe tuh capek pliss kudu ra...
32  NAH cipa juga masukin L occitane sama Kerastas...
33  BosRQ_ skincare dan bodycare udah sekarat untu...
34  Bodycare abis sabun  lotion sekalian beli 2 gr...
35  siapa sih yang bisa nolak promo Beli 2 Gratis ...
36  skincare sama bodycare udah masuk wishlist tin...
37  225k  Diskon beli di link ini httpstcoripRFe7A...
38  LazadaID Di Lazada Ramadan Pesta Gajian aku pe...
39  saphelune_ udh gitu selesainya masih harus ski...
40   Ciara Scar Set aku tuh punya kulit yang sensi...
41  BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...
42  potarisweatt apalg pas bagian bodycare butuh w...
43  aku suka bgt jalanjalan ke alam resikonya bawa...
44  stberryorange drwhiteskincare Pas banget bodyc...
45  selldips skincare bodycare parfum baju tanktop...
46  Oh My Skin  PINK LOVE GLUTA SOAP sabun pencera...
47  potarisweatt tapi kalau pakai skincare bodycar...
48  baru sadar klo jd cewe tuh capek pliss kudu ra...
49  NAH cipa juga masukin L occitane sama Kerastas...
50  BosRQ_ skincare dan bodycare udah sekarat untu...

                                      full_text_clean
0   bodycare abis sabun  lotion sekalian beli 2 gr...
1   siapa sih yang bisa nolak promo beli 2 gratis ...
2   skincare sama bodycare udah masuk wishlist tin...
3   225k  diskon beli di link ini httpstcoriprfe7a...
4   lazadaid di lazada ramadan pesta gajian aku pe...
5   saphelune_ udh gitu selesainya masih harus ski...
6   ciara scar set aku tuh punya kulit yang sensit...
7   beberapa combo bodycare yang paling gong 2026 ...
8   potarisweatt apalg pas bagian bodycare butuh w...
9   aku suka bgt jalanjalan ke alam resikonya bawa...
10  stberryorange drwhiteskincare pas banget bodyc...
11  selldips skincare bodycare parfum baju tanktop...
12  oh my skin  pink love gluta soap sabun pencera...
13  potarisweatt tapi kalau pakai skincare bodycar...
14  baru sadar klo jd cewe tuh capek pliss kudu ra...
15  nah cipa juga masukin l occitane sama kerastas...
16  bosrq_ skincare dan bodycare udah sekarat untu...
17  bodycare abis sabun  lotion sekalian beli 2 gr...
18  siapa sih yang bisa nolak promo beli 2 gratis ...
19  skincare sama bodycare udah masuk wishlist tin...
20  225k  diskon beli di link ini httpstcoriprfe7a...
21  lazadaid di lazada ramadan pesta gajian aku pe...
22  saphelune_ udh gitu selesainya masih harus ski...
23  ciara scar set aku tuh punya kulit yang sensit...
24  beberapa combo bodycare yang paling gong 2026 ...
25  potarisweatt apalg pas bagian bodycare butuh w...
26  aku suka bgt jalanjalan ke alam resikonya bawa...
27  stberryorange drwhiteskincare pas banget bodyc...
28  selldips skincare bodycare parfum baju tanktop...
29  oh my skin  pink love gluta soap sabun pencera...
30  potarisweatt tapi kalau pakai skincare bodycar...
31  baru sadar klo jd cewe tuh capek pliss kudu ra...
32  nah cipa juga masukin l occitane sama kerastas...
33  bosrq_ skincare dan bodycare udah sekarat untu...
34  bodycare abis sabun  lotion sekalian beli 2 gr...
35  siapa sih yang bisa nolak promo beli 2 gratis ...
36  skincare sama bodycare udah masuk wishlist tin...
37  225k  diskon beli di link ini httpstcoriprfe7a...
38  lazadaid di lazada ramadan pesta gajian aku pe...
39  saphelune_ udh gitu selesainya masih harus ski...
40  ciara scar set aku tuh punya kulit yang sensit...
41  beberapa combo bodycare yang paling gong 2026 ...
42  potarisweatt apalg pas bagian bodycare butuh w...
43  aku suka bgt jalanjalan ke alam resikonya bawa...
44  stberryorange drwhiteskincare pas banget bodyc...
45  selldips skincare bodycare parfum baju tanktop...
46  oh my skin  pink love gluta soap sabun pencera...
47  potarisweatt tapi kalau pakai skincare bodycar...
48  baru sadar klo jd cewe tuh capek pliss kudu ra...
49  nah cipa juga masukin l occitane sama kerastas...
50  bosrq_ skincare dan bodycare udah sekarat untu...

In [21]:
#load stop word
stopwords_url = "https://raw.githubusercontent.com/datascienceid/stopwords-bahasa-indonesia/master/stopwords_id_satya.txt"
stopwords = pd.read_csv(stopwords_url, header=None)[0].tolist()
stopwords

['ada',
 'adanya',
 'adalah',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'diantaranya',
 'antara',
 'antaranya',
 'diantara',
 'apa',
 'apaan',
 'mengapa',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'atau',
 'ataukah',
 'ataupun',
 'bagai',
 'bagaikan',
 'sebagai',
 'sebagainya',
 'bagaimana',
 'bagaimanapun',
 'sebagaimana',
 'bagaimanakah',
 'bagi',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'sebaliknya',
 'banyak',
 'sebanyak',
 'beberapa',
 'seberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'sebegini',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'sebegitu',
 'belum',
 'belumlah',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'betulkah',
 'sebetulnya',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'sebisanya',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'cuma',
 'percuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'sedemikian',
 'dengan',
 'depan',
 'di',
 'dia',
 'dialah',
 'dini',
 'diri',
 'dirinya',
 'terdiri',
 'dong',
 'dulu',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'terhadap',
 'terhadapnya',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'harus',
 'haruslah',
 'harusnya',
 'seharusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'sehingga',
 'ia',
 'ialah',
 'ibarat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jangan',
 'jangankan',
 'janganlah',
 'jika',
 'jikalau',
 'juga',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'dikarenakan',
 'karena',
 'karenanya',
 'ke',
 'kecil',
 'kemudian',
 'kenapa',
 'kepada',
 'kepadanya',
 'ketika',
 'seketika',
 'khususnya',
 'kini',
 'kinilah',
 'kiranya',
 'sekiranya',
 'kita',
 'kitalah',
 'kok',
 'lagi',
 'lagian',
 'selagi',
 'lah',
 'lain',
 'lainnya',
 'melainkan',
 'selaku',
 'lalu',
 'melalui',
 'terlalu',
 'lama',
 'lamanya',
 'selama',
 'selama',
 'selamanya',
 'lebih',
 'terlebih',
 'bermacam',
 'macam',
 'semacam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masih',
 'masihkah',
 'semasih',
 'masing',
 'mau',
 'maupun',
 'semaunya',
 'memang',
 'mereka',
 'merekalah',
 'meski',
 'meskipun',
 'semula',
 'mungkin',
 'mungkinkah',
 'nah',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'oleh',
 'olehnya',
 'seorang',
 'seseorang',
 'pada',
 'padanya',
 'padahal',
 'paling',
 'sepanjang',
 'pantas',
 'sepantasnya',
 'sepantasnyalah',
 'para',
 'pasti',
 'pastilah',
 'per',
 'pernah',
 'pula',
 'pun',
 'merupakan',
 'rupanya',
 'serupa',
 'saat',
 'saatnya',
 'sesaat',
 'saja',
 'sajalah',
 'saling',
 'bersama',
 'sama',
 'sesama',
 'sambil',
 'sampai',
 'sana',
 'sangat',
 'sangatlah',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebuah',
 'tersebut',
 'tersebutlah',
 'sedang',
 'sedangkan',
 'sedikit',
 'sedikitnya',
 'segala',
 'segalanya',
 'segera',
 'sesegera',
 'sejak',
 'sejenak',
 'sekali',
 'sekalian',
 'sekalipun',
 'sesekali',
 'sekaligus',
 'sekarang',
 'sekarang',
 'sekitar',
 'sekitarnya',
 'sela',
 'selain',
 'selalu',
 'seluruh',
 'seluruhnya',
 'semakin',
 'sementara',
 'sempat',
 'semua',
 'semuanya',
 'sendiri',
 'sendirinya',
 'seolah',
 'seperti',
 'sepertinya',
 'sering',
 'seringnya',
 'serta',
 'siapa',
 'siapakah',
 'siapapun',
 'disini',
 'disinilah',
 'sini',
 'sinilah',
 'sesuatu',
 'sesuatunya',
 'suatu',
 'sesudah',
 'sesudahnya',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tak',
 'tanpa',
 'setelah',
 'telah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tertentu',
 'seterusnya',
 'tapi',
 'tetapi',
 'setiap',
 'tiap',
 'setidaknya',
 'tidak',
 'tidakkah',
 'tidaklah',
 'toh',
 'waduh',
 'wah',
 'wahai',
 'sewaktu',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakni',
 'yang']

In [22]:
#import library yang dibutuhkan
import re
import json
import requests

In [23]:
# crawl data slang
slang_url = "https://raw.githubusercontent.com/louisowen6/NLP_bahasa_resources/master/combined_slang_words.txt"
response = requests.get(slang_url)
slang_dict = json.loads(response.text)
print(slang_dict)

{'@': 'di', 'abis': 'habis', 'ad': 'ada', 'adlh': 'adalah', 'afaik': 'as far as i know', 'ahaha': 'haha', 'aj': 'saja', 'ajep-ajep': 'dunia gemerlap', 'ak': 'saya', 'akika': 'aku', 'akkoh': 'aku', 'akuwh': 'aku', 'alay': 'norak', 'alow': 'halo', 'ambilin': 'ambilkan', 'ancur': 'hancur', 'anjrit': 'anjing', 'anter': 'antar', 'ap2': 'apa-apa', 'apasih': 'apa sih', 'apes': 'sial', 'aps': 'apa', 'aq': 'saya', 'aquwh': 'aku', 'asbun': 'asal bunyi', 'aseekk': 'asyik', 'asekk': 'asyik', 'asem': 'asam', 'aspal': 'asli tetapi palsu', 'astul': 'asal tulis', 'ato': 'atau', 'au ah': 'tidak mau tahu', 'awak': 'saya', 'ay': 'sayang', 'ayank': 'sayang', 'b4': 'sebelum', 'bakalan': 'akan', 'bandes': 'bantuan desa', 'bangedh': 'banget', 'banpol': 'bantuan polisi', 'banpur': 'bantuan tempur', 'basbang': 'basi', 'bcanda': 'bercanda', 'bdg': 'bandung', 'begajulan': 'nakal', 'beliin': 'belikan', 'bencong': 'banci', 'bentar': 'sebentar', 'ber3': 'bertiga', 'beresin': 'membereskan', 'bete': 'bosan', 'beud': 'banget', 'bg': 'abang', 'bgmn': 'bagaimana', 'bgt': 'banget', 'bijimane': 'bagaimana', 'bintal': 'bimbingan mental', 'bkl': 'akan', 'bknnya': 'bukannya', 'blegug': 'bodoh', 'blh': 'boleh', 'bln': 'bulan', 'blum': 'belum', 'bnci': 'benci', 'bnran': 'yang benar', 'bodor': 'lucu', 'bokap': 'ayah', 'boker': 'buang air besar', 'bokis': 'bohong', 'boljug': 'boleh juga', 'bonek': 'bocah nekat', 'boyeh': 'boleh', 'br': 'baru', 'brg': 'bareng', 'bro': 'saudara laki-laki', 'bru': 'baru', 'bs': 'bisa', 'bsen': 'bosan', 'bt': 'buat', 'btw': 'ngomong-ngomong', 'buaya': 'tidak setia', 'bubbu': 'tidur', 'bubu': 'tidur', 'bumil': 'ibu hamil', 'bw': 'bawa', 'bwt': 'buat', 'byk': 'banyak', 'byrin': 'bayarkan', 'cabal': 'sabar', 'cadas': 'keren', 'calo': 'makelar', 'can': 'belum', 'capcus': 'pergi', 'caper': 'cari perhatian', 'ce': 'cewek', 'cekal': 'cegah tangkal', 'cemen': 'penakut', 'cengengesan': 'tertawa', 'cepet': 'cepat', 'cew': 'cewek', 'chuyunk': 'sayang', 'cimeng': 'ganja', 'cipika cipiki': 'cium pipi kanan cium pipi kiri', 'ciyh': 'sih', 'ckepp': 'cakep', 'ckp': 'cakep', 'cmiiw': "correct me if i'm wrong", 'cmpur': 'campur', 'cong': 'banci', 'conlok': 'cinta lokasi', 'cowwyy': 'maaf', 'cp': 'siapa', 'cpe': 'capek', 'cppe': 'capek', 'cucok': 'cocok', 'cuex': 'cuek', 'cumi': 'Cuma miscall', 'cups': 'culun', 'curanmor': 'pencurian kendaraan bermotor', 'curcol': 'curahan hati colongan', 'cwek': 'cewek', 'cyin': 'cinta', 'd': 'di', 'dah': 'deh', 'dapet': 'dapat', 'de': 'adik', 'dek': 'adik', 'demen': 'suka', 'deyh': 'deh', 'dgn': 'dengan', 'diancurin': 'dihancurkan', 'dimaafin': 'dimaafkan', 'dimintak': 'diminta', 'disono': 'di sana', 'dket': 'dekat', 'dkk': 'dan kawan-kawan', 'dll': 'dan lain-lain', 'dlu': 'dulu', 'dngn': 'dengan', 'dodol': 'bodoh', 'doku': 'uang', 'dongs': 'dong', 'dpt': 'dapat', 'dri': 'dari', 'drmn': 'darimana', 'drtd': 'dari tadi', 'dst': 'dan seterusnya', 'dtg': 'datang', 'duh': 'aduh', 'duren': 'durian', 'ed': 'edisi', 'egp': 'emang gue pikirin', 'eke': 'aku', 'elu': 'kamu', 'emangnya': 'memangnya', 'emng': 'memang', 'endak': 'tidak', 'enggak': 'tidak', 'envy': 'iri', 'ex': 'mantan', 'fax': 'facsimile', 'fifo': 'first in first out', 'folbek': 'follow back', 'fyi': 'sebagai informasi', 'gaada': 'tidak ada uang', 'gag': 'tidak', 'gaje': 'tidak jelas', 'gak papa': 'tidak apa-apa', 'gan': 'juragan', 'gaptek': 'gagap teknologi', 'gatek': 'gagap teknologi', 'gawe': 'kerja', 'gbs': 'tidak bisa', 'gebetan': 'orang yang disuka', 'geje': 'tidak jelas', 'gepeng': 'gelandangan dan pengemis', 'ghiy': 'lagi', 'gile': 'gila', 'gimana': 'bagaimana', 'gino': 'gigi nongol', 'githu': 'gitu', 'gj': 'tidak jelas', 'gmana': 'bagaimana', 'gn': 'begini', 'goblok': 'bodoh', 'golput': 'golongan putih', 'gowes': 'mengayuh sepeda', 'gpny': 'tidak punya', 'gr': 'gede rasa', 'gretongan': 'gratisan', 'gtau': 'tidak tahu', 'gua': 'saya', 'guoblok': 'goblok', 'gw': 'saya', 'ha': 'tertawa', 'haha': 'tertawa', 'hallow': 'halo', 'hankam': 'pertahanan dan keamanan', 'hehe': 'he', 'helo': 'halo', 'hey': 'hai', 'hlm': 'halaman', 'hny': 'hanya', 'hoax': 'isu bohong', 'hr': 'hari', 'hrus': 'harus', 'hubdar': 'perhubungan darat', 'huff': 'mengeluh', 'hum': 'rumah', 'humz': 'rumah', 'ilang': 'hilang', 'ilfil': 'tidak suka', 'imho': 'in my humble opinion', 'imoetz': 'imut', 'item': 'hitam', 'itungan': 'hitungan', 'iye': 'iya', 'ja': 'saja', 'jadiin': 'jadi', 'jaim': 'jaga image', 'jayus': 'tidak lucu', 'jdi': 'jadi', 'jem': 'jam', 'jga': 'juga', 'jgnkan': 'jangankan', 'jir': 'anjing', 'jln': 'jalan', 'jomblo': 'tidak punya pacar', 'jubir': 'juru bicara', 'jutek': 'galak', 'k': 'ke', 'kab': 'kabupaten', 'kabor': 'kabur', 'kacrut': 'kacau', 'kadiv': 'kepala divisi', 'kagak': 'tidak', 'kalo': 'kalau', 'kampret': 'sialan', 'kamtibmas': 'keamanan dan ketertiban masyarakat', 'kamuwh': 'kamu', 'kanwil': 'kantor wilayah', 'karna': 'karena', 'kasubbag': 'kepala subbagian', 'katrok': 'kampungan', 'kayanya': 'kayaknya', 'kbr': 'kabar', 'kdu': 'harus', 'kec': 'kecamatan', 'kejurnas': 'kejuaraan nasional', 'kekeuh': 'keras kepala', 'kel': 'kelurahan', 'kemaren': 'kemarin', 'kepengen': 'mau', 'kepingin': 'mau', 'kepsek': 'kepala sekolah', 'kesbang': 'kesatuan bangsa', 'kesra': 'kesejahteraan rakyat', 'ketrima': 'diterima', 'kgiatan': 'kegiatan', 'kibul': 'bohong', 'kimpoi': 'kawin', 'kl': 'kalau', 'klianz': 'kalian', 'kloter': 'kelompok terbang', 'klw': 'kalau', 'km': 'kamu', 'kmps': 'kampus', 'kmrn': 'kemarin', 'knal': 'kenal', 'knp': 'kenapa', 'kodya': 'kota madya', 'komdis': 'komisi disiplin', 'komsov': 'komunis sovyet', 'kongkow': 'kumpul bareng teman-teman', 'kopdar': 'kopi darat', 'korup': 'korupsi', 'kpn': 'kapan', 'krenz': 'keren', 'krm': 'kirim', 'kt': 'kita', 'ktmu': 'ketemu', 'ktr': 'kantor', 'kuper': 'kurang pergaulan', 'kw': 'imitasi', 'kyk': 'seperti', 'la': 'lah', 'lam': 'salam', 'lamp': 'lampiran', 'lanud': 'landasan udara', 'latgab': 'latihan gabungan', 'lebay': 'berlebihan', 'leh': 'boleh', 'lelet': 'lambat', 'lemot': 'lambat', 'lgi': 'lagi', 'lgsg': 'langsung', 'liat': 'lihat', 'litbang': 'penelitian dan pengembangan', 'lmyn': 'lumayan', 'lo': 'kamu', 'loe': 'kamu', 'lola': 'lambat berfikir', 'louph': 'cinta', 'low': 'kalau', 'lp': 'lupa', 'luber': 'langsung, umum, bebas, dan rahasia', 'luchuw': 'lucu', 'lum': 'belum', 'luthu': 'lucu', 'lwn': 'lawan', 'maacih': 'terima kasih', 'mabal': 'bolos', 'macem': 'macam', 'macih': 'masih', 'maem': 'makan', 'magabut': 'makan gaji buta', 'maho': 'homo', 'mak jang': 'kaget', 'maksain': 'memaksa', 'malem': 'malam', 'mam': 'makan', 'maneh': 'kamu', 'maniez': 'manis', 'mao': 'mau', 'masukin': 'masukkan', 'melu': 'ikut', 'mepet': 'dekat sekali', 'mgu': 'minggu', 'migas': 'minyak dan gas bumi', 'mikol': 'minuman beralkohol', 'miras': 'minuman keras', 'mlah': 'malah', 'mngkn': 'mungkin', 'mo': 'mau', 'mokad': 'mati', 'moso': 'masa', 'mpe': 'sampai', 'msk': 'masuk', 'mslh': 'masalah', 'mt': 'makan teman', 'mubes': 'musyawarah besar', 'mulu': 'melulu', 'mumpung': 'selagi', 'munas': 'musyawarah nasional', 'muntaber': 'muntah dan berak', 'musti': 'mesti', 'muupz': 'maaf', 'mw': 'now watching', 'n': 'dan', 'nanam': 'menanam', 'nanya': 'bertanya', 'napa': 'kenapa', 'napi': 'narapidana', 'napza': 'narkotika, alkohol, psikotropika, dan zat adiktif ', 'narkoba': 'narkotika, psikotropika, dan obat terlarang', 'nasgor': 'nasi goreng', 'nda': 'tidak', 'ndiri': 'sendiri', 'ne': 'ini', 'nekolin': 'neokolonialisme', 'nembak': 'menyatakan cinta', 'ngabuburit': 'menunggu berbuka puasa', 'ngaku': 'mengaku', 'ngambil': 'mengambil', 'nganggur': 'tidak punya pekerjaan', 'ngapah': 'kenapa', 'ngaret': 'terlambat', 'ngasih': 'memberikan', 'ngebandel': 'berbuat bandel', 'ngegosip': 'bergosip', 'ngeklaim': 'mengklaim', 'ngeksis': 'menjadi eksis', 'ngeles': 'berkilah', 'ngelidur': 'menggigau', 'ngerampok': 'merampok', 'ngga': 'tidak', 'ngibul': 'berbohong', 'ngiler': 'mau', 'ngiri': 'iri', 'ngisiin': 'mengisikan', 'ngmng': 'bicara', 'ngomong': 'bicara', 'ngubek2': 'mencari-cari', 'ngurus': 'mengurus', 'nie': 'ini', 'nih': 'ini', 'niyh': 'nih', 'nmr': 'nomor', 'nntn': 'nonton', 'nobar': 'nonton bareng', 'np': 'now playing', 'ntar': 'nanti', 'ntn': 'nonton', 'numpuk': 'bertumpuk', 'nutupin': 'menutupi', 'nyari': 'mencari', 'nyekar': 'menyekar', 'nyicil': 'mencicil', 'nyoblos': 'mencoblos', 'nyokap': 'ibu', 'ogah': 'tidak mau', 'ol': 'online', 'ongkir': 'ongkos kirim', 'oot': 'out of topic', 'org2': 'orang-orang', 'ortu': 'orang tua', 'otda': 'otonomi daerah', 'otw': 'on the way, sedang di jalan', 'pacal': 'pacar', 'pake': 'pakai', 'pala': 'kepala', 'pansus': 'panitia khusus', 'parpol': 'partai politik', 'pasutri': 'pasangan suami istri', 'pd': 'pada', 'pede': 'percaya diri', 'pelatnas': 'pemusatan latihan nasional', 'pemda': 'pemerintah daerah', 'pemkot': 'pemerintah kota', 'pemred': 'pemimpin redaksi', 'penjas': 'pendidikan jasmani', 'perda': 'peraturan daerah', 'perhatiin': 'perhatikan', 'pesenan': 'pesanan', 'pgang': 'pegang', 'pi': 'tapi', 'pilkada': 'pemilihan kepala daerah', 'pisan': 'sangat', 'pk': 'penjahat kelamin', 'plg': 'paling', 'pmrnth': 'pemerintah', 'polantas': 'polisi lalu lintas', 'ponpes': 'pondok pesantren', 'pp': 'pulang pergi', 'prg': 'pergi', 'prnh': 'pernah', 'psen': 'pesan', 'pst': 'pasti', 'pswt': 'pesawat', 'pw': 'posisi nyaman', 'qmu': 'kamu', 'rakor': 'rapat koordinasi', 'ranmor': 'kendaraan bermotor', 're': 'reply', 'ref': 'referensi', 'rehab': 'rehabilitasi', 'rempong': 'sulit', 'repp': 'balas', 'restik': 'reserse narkotika', 'rhs': 'rahasia', 'rmh': 'rumah', 'ru': 'baru', 'ruko': 'rumah toko', 'rusunawa': 'rumah susun sewa', 'ruz': 'terus', 'saia': 'saya', 'salting': 'salah tingkah', 'sampe': 'sampai', 'samsek': 'sama sekali', 'sapose': 'siapa', 'satpam': 'satuan pengamanan', 'sbb': 'sebagai berikut', 'sbh': 'sebuah', 'sbnrny': 'sebenarnya', 'scr': 'secara', 'sdgkn': 'sedangkan', 'sdkt': 'sedikit', 'se7': 'setuju', 'sebelas dua belas': 'mirip', 'sembako': 'sembilan bahan pokok', 'sempet': 'sempat', 'sendratari': 'seni drama tari', 'sgt': 'sangat', 'shg': 'sehingga', 'siech': 'sih', 'sikon': 'situasi dan kondisi', 'sinetron': 'sinema elektronik', 'siramin': 'siramkan', 'sj': 'saja', 'skalian': 'sekalian', 'sklh': 'sekolah', 'skt': 'sakit', 'slesai': 'selesai', 'sll': 'selalu', 'slma': 'selama', 'slsai': 'selesai', 'smpt': 'sempat', 'smw': 'semua', 'sndiri': 'sendiri', 'soljum': 'sholat jumat', 'songong': 'sombong', 'sory': 'maaf', 'sosek': 'sosial-ekonomi', 'sotoy': 'sok tahu', 'spa': 'siapa', 'sppa': 'siapa', 'spt': 'seperti', 'srtfkt': 'sertifikat', 'stiap': 'setiap', 'stlh': 'setelah', 'suk': 'masuk', 'sumpek': 'sempit', 'syg': 'sayang', 't4': 'tempat', 'tajir': 'kaya', 'tau': 'tahu', 'taw': 'tahu', 'td': 'tadi', 'tdk': 'tidak', 'teh': 'kakak perempuan', 'telat': 'terlambat', 'telmi': 'telat berpikir', 'temen': 'teman', 'tengil': 'menyebalkan', 'tepar': 'terkapar', 'tggu': 'tunggu', 'tgu': 'tunggu', 'thankz': 'terima kasih', 'thn': 'tahun', 'tilang': 'bukti pelanggaran', 'tipiwan': 'TvOne', 'tks': 'terima kasih', 'tlp': 'telepon', 'tls': 'tulis', 'tmbah': 'tambah', 'tmen2': 'teman-teman', 'tmpah': 'tumpah', 'tmpt': 'tempat', 'tngu': 'tunggu', 'tnyta': 'ternyata', 'tokai': 'tai', 'toserba': 'toko serba ada', 'tpi': 'tapi', 'trdhulu': 'terdahulu', 'trima': 'terima kasih', 'trm': 'terima', 'trs': 'terus', 'trutama': 'terutama', 'ts': 'penulis', 'tst': 'tahu sama tahu', 'ttg': 'tentang', 'tuch': 'tuh', 'tuir': 'tua', 'tw': 'tahu', 'u': 'kamu', 'ud': 'sudah', 'udah': 'sudah', 'ujg': 'ujung', 'ul': 'ulangan', 'unyu': 'lucu', 'uplot': 'unggah', 'urang': 'saya', 'usah': 'perlu', 'utk': 'untuk', 'valas': 'valuta asing', 'w/': 'dengan', 'wadir': 'wakil direktur', 'wamil': 'wajib militer', 'warkop': 'warung kopi', 'warteg': 'warung tegal', 'wat': 'buat', 'wkt': 'waktu', 'wtf': 'what the fuck', 'xixixi': 'tertawa', 'ya': 'iya', 'yap': 'iya', 'yaudah': 'ya sudah', 'yawdah': 'ya sudah', 'yg': 'yang', 'yl': 'yang lain', 'yo': 'iya', 'yowes': 'ya sudah', 'yup': 'iya', '7an': 'tujuan', 'ababil': 'abg labil', 'acc': 'accord', 'adlah': 'adalah', 'adoh': 'aduh', 'aha': 'tertawa', 'aing': 'saya', 'aja': 'saja', 'ajj': 'saja', 'aka': 'dikenal juga sebagai', 'akko': 'aku', 'akku': 'aku', 'akyu': 'aku', 'aljasa': 'asal jadi saja', 'ama': 'sama', 'ambl': 'ambil', 'anjir': 'anjing', 'ank': 'anak', 'ap': 'apa', 'apaan': 'apa', 'ape': 'apa', 'aplot': 'unggah', 'apva': 'apa', 'aqu': 'aku', 'asap': 'sesegera mungkin', 'aseek': 'asyik', 'asek': 'asyik', 'aseknya': 'asyiknya', 'asoy': 'asyik', 'astrojim': 'astagfirullahaladzim', 'ath': 'kalau begitu', 'atuh': 'kalau begitu', 'ava': 'avatar', 'aws': 'awas', 'ayang': 'sayang', 'ayok': 'ayo', 'bacot': 'banyak bicara', 'bales': 'balas', 'bangdes': 'pembangunan desa', 'bangkotan': 'tua', 'banpres': 'bantuan presiden', 'bansarkas': 'bantuan sarana kesehatan', 'bazis': 'badan amal, zakat, infak, dan sedekah', 'bcoz': 'karena', 'beb': 'sayang', 'bejibun': 'banyak', 'belom': 'belum', 'bener': 'benar', 'ber2': 'berdua', 'berdikari': 'berdiri di atas kaki sendiri', 'bet': 'banget', 'beti': 'beda tipis', 'beut': 'banget', 'bgd': 'banget', 'bgs': 'bagus', 'bhubu': 'tidur', 'bimbuluh': 'bimbingan dan penyuluhan', 'bisi': 'kalau-kalau', 'bkn': 'bukan', 'bl': 'beli', 'blg': 'bilang', 'blm': 'belum', 'bls': 'balas', 'bnchi': 'benci', 'bngung': 'bingung', 'bnyk': 'banyak', 'bohay': 'badan aduhai', 'bokep': 'porno', 'bokin': 'pacar', 'bole': 'boleh', 'bolot': 'bodoh', 'bonyok': 'ayah ibu', 'bpk': 'bapak', 'brb': 'segera kembali', 'brngkt': 'berangkat', 'brp': 'berapa', 'brur': 'saudara laki-laki', 'bsa': 'bisa', 'bsk': 'besok', 'bu_bu': 'tidur', 'bubarin': 'bubarkan', 'buber': 'buka bersama', 'bujubune': 'luar biasa', 'buser': 'buru sergap', 'bwhn': 'bawahan', 'byar': 'bayar', 'byr': 'bayar', 'c8': 'chat', 'cabut': 'pergi', 'caem': 'cakep', 'cama-cama': 'sama-sama', 'cangcut': 'celana dalam', 'cape': 'capek', 'caur': 'jelek', 'cekak': 'tidak ada uang', 'cekidot': 'coba lihat', 'cemplungin': 'cemplungkan', 'ceper': 'pendek', 'ceu': 'kakak perempuan', 'cewe': 'cewek', 'cibuk': 'sibuk', 'cin': 'cinta', 'ciye': 'cie', 'ckck': 'ck', 'clbk': 'cinta lama bersemi kembali', 'cmpr': 'campur', 'cnenk': 'senang', 'congor': 'mulut', 'cow': 'cowok', 'coz': 'karena', 'cpa': 'siapa', 'gokil': 'gila', 'gombal': 'suka merayu', 'gpl': 'tidak pakai lama', 'gpp': 'tidak apa-apa', 'gretong': 'gratis', 'gt': 'begitu', 'gtw': 'tidak tahu', 'gue': 'saya', 'guys': 'teman-teman', 'gws': 'cepat sembuh', 'haghaghag': 'tertawa', 'hakhak': 'tertawa', 'handak': 'bahan peledak', 'hansip': 'pertahanan sipil', 'hellow': 'halo', 'helow': 'halo', 'hi': 'hai', 'hlng': 'hilang', 'hnya': 'hanya', 'houm': 'rumah', 'hrs': 'harus', 'hubad': 'hubungan angkatan darat', 'hubla': 'perhubungan laut', 'huft': 'mengeluh', 'humas': 'hubungan masyarakat', 'idk': 'saya tidak tahu', 'ilfeel': 'tidak suka', 'imba': 'jago sekali', 'imoet': 'imut', 'info': 'informasi', 'itung': 'hitung', 'isengin': 'bercanda', 'iyala': 'iya lah', 'iyo': 'iya', 'jablay': 'jarang dibelai', 'jadul': 'jaman dulu', 'jancuk': 'anjing', 'jd': 'jadi', 'jdikan': 'jadikan', 'jg': 'juga', 'jgn': 'jangan', 'jijay': 'jijik', 'jkt': 'jakarta', 'jnj': 'janji', 'jth': 'jatuh', 'jurdil': 'jujur adil', 'jwb': 'jawab', 'ka': 'kakak', 'kabag': 'kepala bagian', 'kacian': 'kasihan', 'kadit': 'kepala direktorat', 'kaga': 'tidak', 'kaka': 'kakak', 'kamtib': 'keamanan dan ketertiban', 'kamuh': 'kamu', 'kamyu': 'kamu', 'kapt': 'kapten', 'kasat': 'kepala satuan', 'kasubbid': 'kepala subbidang', 'kau': 'kamu', 'kbar': 'kabar', 'kcian': 'kasihan', 'keburu': 'terlanjur', 'kedubes': 'kedutaan besar', 'kek': 'seperti', 'keknya': 'kayaknya', 'keliatan': 'kelihatan', 'keneh': 'masih', 'kepikiran': 'terpikirkan', 'kepo': 'mau tahu urusan orang', 'kere': 'tidak punya uang', 'kesian': 'kasihan', 'ketauan': 'ketahuan', 'keukeuh': 'keras kepala', 'khan': 'kan', 'kibus': 'kaki busuk', 'kk': 'kakak', 'klian': 'kalian', 'klo': 'kalau', 'kluarga': 'keluarga', 'klwrga': 'keluarga', 'kmari': 'kemari', 'kmpus': 'kampus', 'kn': 'kan', 'knl': 'kenal', 'knpa': 'kenapa', 'kog': 'kok', 'kompi': 'komputer', 'komtiong': 'komunis Tiongkok', 'konjen': 'konsulat jenderal', 'koq': 'kok', 'kpd': 'kepada', 'kptsan': 'keputusan', 'krik': 'garing', 'krn': 'karena', 'ktauan': 'ketahuan', 'ktny': 'katanya', 'kudu': 'harus', 'kuq': 'kok', 'ky': 'seperti', 'kykny': 'kayanya', 'laka': 'kecelakaan', 'lambreta': 'lambat', 'lansia': 'lanjut usia', 'lapas': 'lembaga pemasyarakatan', 'lbur': 'libur', 'lekong': 'laki-laki', 'lg': 'lagi', 'lgkp': 'lengkap', 'lht': 'lihat', 'linmas': 'perlindungan masyarakat', 'lmyan': 'lumayan', 'lngkp': 'lengkap', 'loch': 'loh', 'lol': 'tertawa', 'lom': 'belum', 'loupz': 'cinta', 'lowh': 'kamu', 'lu': 'kamu', 'luchu': 'lucu', 'luff': 'cinta', 'luph': 'cinta', 'lw': 'kamu', 'lwt': 'lewat', 'maaciw': 'terima kasih', 'mabes': 'markas besar', 'macem-macem': 'macam-macam', 'madesu': 'masa depan suram', 'maen': 'main', 'mahatma': 'maju sehat bersama', 'mak': 'ibu', 'makasih': 'terima kasih', 'malah': 'bahkan', 'malu2in': 'memalukan', 'mamz': 'makan', 'manies': 'manis', 'mantep': 'mantap', 'markus': 'makelar kasus', 'mba': 'mbak', 'mending': 'lebih baik', 'mgkn': 'mungkin', 'mhn': 'mohon', 'miker': 'minuman keras', 'milis': 'mailing list', 'mksd': 'maksud', 'mls': 'malas', 'mnt': 'minta', 'moge': 'motor gede', 'mokat': 'mati', 'mosok': 'masa', 'msh': 'masih', 'mskpn': 'meskipun', 'msng2': 'masing-masing', 'muahal': 'mahal', 'muker': 'musyawarah kerja', 'mumet': 'pusing', 'muna': 'munafik', 'munaslub': 'musyawarah nasional luar biasa', 'musda': 'musyawarah daerah', 'muup': 'maaf', 'muuv': 'maaf', 'nal': 'kenal', 'nangis': 'menangis', 'naon': 'apa', 'napol': 'narapidana politik', 'naq': 'anak', 'narsis': 'bangga pada diri sendiri', 'nax': 'anak', 'ndak': 'tidak', 'ndut': 'gendut', 'nekolim': 'neokolonialisme', 'nelfon': 'menelepon', 'ngabis2in': 'menghabiskan', 'ngakak': 'tertawa', 'ngambek': 'marah', 'ngampus': 'pergi ke kampus', 'ngantri': 'mengantri', 'ngapain': 'sedang apa', 'ngaruh': 'berpengaruh', 'ngawur': 'berbicara sembarangan', 'ngeceng': 'kumpul bareng-bareng', 'ngeh': 'sadar', 'ngekos': 'tinggal di kos', 'ngelamar': 'melamar', 'ngeliat': 'melihat', 'ngemeng': 'bicara terus-terusan', 'ngerti': 'mengerti', 'nggak': 'tidak', 'ngikut': 'ikut', 'nginep': 'menginap', 'ngisi': 'mengisi', 'ngmg': 'bicara', 'ngocol': 'lucu', 'ngomongin': 'membicarakan', 'ngumpul': 'berkumpul', 'ni': 'ini', 'nyasar': 'tersesat', 'nyariin': 'mencari', 'nyiapin': 'mempersiapkan', 'nyiram': 'menyiram', 'nyok': 'ayo', 'o/': 'oleh', 'ok': 'ok', 'priksa': 'periksa', 'pro': 'profesional', 'psn': 'pesan', 'psti': 'pasti', 'puanas': 'panas', 'qmo': 'kamu', 'qt': 'kita', 'rame': 'ramai', 'raskin': 'rakyat miskin', 'red': 'redaksi', 'reg': 'register', 'rejeki': 'rezeki', 'renstra': 'rencana strategis', 'reskrim': 'reserse kriminal', 'sni': 'sini', 'somse': 'sombong sekali', 'sorry': 'maaf', 'sosbud': 'sosial-budaya', 'sospol': 'sosial-politik', 'sowry': 'maaf', 'spd': 'sepeda', 'sprti': 'seperti', 'spy': 'supaya', 'stelah': 'setelah', 'subbag': 'subbagian', 'sumbangin': 'sumbangkan', 'sy': 'saya', 'syp': 'siapa', 'tabanas': 'tabungan pembangunan nasional', 'tar': 'nanti', 'taun': 'tahun', 'tawh': 'tahu', 'tdi': 'tadi', 'te2p': 'tetap', 'tekor': 'rugi', 'telkom': 'telekomunikasi', 'telp': 'telepon', 'temen2': 'teman-teman', 'tengok': 'menjenguk', 'terbitin': 'terbitkan', 'tgl': 'tanggal', 'thanks': 'terima kasih', 'thd': 'terhadap', 'thx': 'terima kasih', 'tipi': 'TV', 'tkg': 'tukang', 'tll': 'terlalu', 'tlpn': 'telepon', 'tman': 'teman', 'tmbh': 'tambah', 'tmn2': 'teman-teman', 'tmph': 'tumpah', 'tnda': 'tanda', 'tnh': 'tanah', 'togel': 'toto gelap', 'tp': 'tapi', 'tq': 'terima kasih', 'trgntg': 'tergantung', 'trims': 'terima kasih', 'cb': 'coba', 'y': 'ya', 'munfik': 'munafik', 'reklamuk': 'reklamasi', 'sma': 'sama', 'tren': 'trend', 'ngehe': 'kesal', 'mz': 'mas', 'analisise': 'analisis', 'sadaar': 'sadar', 'sept': 'september', 'nmenarik': 'menarik', 'zonk': 'bodoh'

In [25]:
#install sastrawi untuk bahasa indonesia
%pip install Sastrawi

Requirement already satisfied: Sastrawi in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (1.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
#import library sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [27]:
#using sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [31]:
def clean_full_text(text):

    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'(.)\1{2,}', r'\1', text)
    words = text.split()

    # normalisasi slang
    words = [slang_dict[word] if word in slang_dict else word for word in words]


    text = " ".join(words)

    # stemming
    text = stemmer.stem(text)

    return text

In [32]:
# ==============================
# 8. Jalankan Pipeline
# ==============================
df['clean_full_text'] = df['full_text'].apply(clean_full_text)

print(df[['full_text', 'clean_full_text']])

                                            full_text  \
0   Bodycare abis sabun  lotion sekalian beli 2 gr...
1   siapa sih yang bisa nolak promo Beli 2 Gratis ...
2   skincare sama bodycare udah masuk wishlist tin...
3   225k  Diskon beli di link ini httpstcoripRFe7A...
4   LazadaID Di Lazada Ramadan Pesta Gajian aku pe...
5   saphelune_ udh gitu selesainya masih harus ski...
6    Ciara Scar Set aku tuh punya kulit yang sensi...
7   BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...
8   potarisweatt apalg pas bagian bodycare butuh w...
9   aku suka bgt jalanjalan ke alam resikonya bawa...
10  stberryorange drwhiteskincare Pas banget bodyc...
11  selldips skincare bodycare parfum baju tanktop...
12  Oh My Skin  PINK LOVE GLUTA SOAP sabun pencera...
13  potarisweatt tapi kalau pakai skincare bodycar...
14  baru sadar klo jd cewe tuh capek pliss kudu ra...
15  NAH cipa juga masukin L occitane sama Kerastas...
16  BosRQ_ skincare dan bodycare udah sekarat untu...
17  Bodycare abis sabun  lotion sekalian beli 2 gr...
18  siapa sih yang bisa nolak promo Beli 2 Gratis ...
19  skincare sama bodycare udah masuk wishlist tin...
20  225k  Diskon beli di link ini httpstcoripRFe7A...
21  LazadaID Di Lazada Ramadan Pesta Gajian aku pe...
22  saphelune_ udh gitu selesainya masih harus ski...
23   Ciara Scar Set aku tuh punya kulit yang sensi...
24  BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...
25  potarisweatt apalg pas bagian bodycare butuh w...
26  aku suka bgt jalanjalan ke alam resikonya bawa...
27  stberryorange drwhiteskincare Pas banget bodyc...
28  selldips skincare bodycare parfum baju tanktop...
29  Oh My Skin  PINK LOVE GLUTA SOAP sabun pencera...
30  potarisweatt tapi kalau pakai skincare bodycar...
31  baru sadar klo jd cewe tuh capek pliss kudu ra...
32  NAH cipa juga masukin L occitane sama Kerastas...
33  BosRQ_ skincare dan bodycare udah sekarat untu...
34  Bodycare abis sabun  lotion sekalian beli 2 gr...
35  siapa sih yang bisa nolak promo Beli 2 Gratis ...
36  skincare sama bodycare udah masuk wishlist tin...
37  225k  Diskon beli di link ini httpstcoripRFe7A...
38  LazadaID Di Lazada Ramadan Pesta Gajian aku pe...
39  saphelune_ udh gitu selesainya masih harus ski...
40   Ciara Scar Set aku tuh punya kulit yang sensi...
41  BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...
42  potarisweatt apalg pas bagian bodycare butuh w...
43  aku suka bgt jalanjalan ke alam resikonya bawa...
44  stberryorange drwhiteskincare Pas banget bodyc...
45  selldips skincare bodycare parfum baju tanktop...
46  Oh My Skin  PINK LOVE GLUTA SOAP sabun pencera...
47  potarisweatt tapi kalau pakai skincare bodycar...
48  baru sadar klo jd cewe tuh capek pliss kudu ra...
49  NAH cipa juga masukin L occitane sama Kerastas...
50  BosRQ_ skincare dan bodycare udah sekarat untu...

                                      clean_full_text
0   bodycare habis sabun lotion sekali beli 2 grat...
1   siapa sih yang bisa nolak promo beli 2 gratis ...
2   skincare sama bodycare sudah masuk wishlist ti...
3   225k diskon beli di link ini httpstcoriprfe7ap...
4   lazadaid di lazada ramadan pesta gaji aku ken ...
5   saphelune udh gitu selesai masih harus skincar...
6   ciara scar set aku tuh punya kulit yang sensit...
7   beberapa combo bodycare yang paling gong 2026 ...
8   potarisweatt apalg pas bagi bodycare butuh wak...
9   aku suka banget jalanjalan ke alam resiko bawa...
10  stberryorange drwhiteskincare pas banget bodyc...
11  selldips skincare bodycare parfum baju tanktop...
12  oh my skin pink love gluta soap sabun cerah ba...
13  potarisweatt tapi kalau pakai skincare bodycar...
14  baru sadar kalau jadi cewek tuh capek pliss ha...
15  nah cipa juga masuk l occitane sama kerastase ...
16  bosrq skincare dan bodycare sudah sekarat untu...
17  bodycare habis sabun lotion sekali beli 2 grat...
18  siapa sih yang bisa nolak promo beli 2 gratis ...
19  skincare sama bodycare sudah masuk wishlist ti...
20  225k diskon beli di link ini httpstcoriprfe7ap...
21  lazadaid di lazada ramadan pesta gaji aku ken ...
22  saphelune udh gitu selesai masih harus skincar...
23  ciara scar set aku tuh punya kulit yang sensit...
24  beberapa combo bodycare yang paling gong 2026 ...
25  potarisweatt apalg pas bagi bodycare butuh wak...
26  aku suka banget jalanjalan ke alam resiko bawa...
27  stberryorange drwhiteskincare pas banget bodyc...
28  selldips skincare bodycare parfum baju tanktop...
29  oh my skin pink love gluta soap sabun cerah ba...
30  potarisweatt tapi kalau pakai skincare bodycar...
31  baru sadar kalau jadi cewek tuh capek pliss ha...
32  nah cipa juga masuk l occitane sama kerastase ...
33  bosrq skincare dan bodycare sudah sekarat untu...
34  bodycare habis sabun lotion sekali beli 2 grat...
35  siapa sih yang bisa nolak promo beli 2 gratis ...
36  skincare sama bodycare sudah masuk wishlist ti...
37  225k diskon beli di link ini httpstcoriprfe7ap...
38  lazadaid di lazada ramadan pesta gaji aku ken ...
39  saphelune udh gitu selesai masih harus skincar...
40  ciara scar set aku tuh punya kulit yang sensit...
41  beberapa combo bodycare yang paling gong 2026 ...
42  potarisweatt apalg pas bagi bodycare butuh wak...
43  aku suka banget jalanjalan ke alam resiko bawa...
44  stberryorange drwhiteskincare pas banget bodyc...
45  selldips skincare bodycare parfum baju tanktop...
46  oh my skin pink love gluta soap sabun cerah ba...
47  potarisweatt tapi kalau pakai skincare bodycar...
48  baru sadar kalau jadi cewek tuh capek pliss ha...
49  nah cipa juga masuk l occitane sama kerastase ...
50  bosrq skincare dan bodycare sudah sekarat untu...

In [33]:
import spacy
nlp = spacy.blank("id")  # tokenizer saja

def spacy_tokenize(text):
    doc = nlp(text)
    return [token.text for token in doc]

df['tokens'] = df['clean_full_text'].apply(spacy_tokenize)

In [35]:
df

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username,full_text_clean,clean_full_text,tokens
0,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,Bodycare abis sabun lotion sekalian beli 2 gr...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN,bodycare abis sabun lotion sekalian beli 2 gr...,bodycare habis sabun lotion sekali beli 2 grat...,"[bodycare, habis, sabun, lotion, sekali, beli,..."
1,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo Beli 2 Gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN,siapa sih yang bisa nolak promo beli 2 gratis ...,siapa sih yang bisa nolak promo beli 2 gratis ...,"[siapa, sih, yang, bisa, nolak, promo, beli, 2..."
2,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN,skincare sama bodycare udah masuk wishlist tin...,skincare sama bodycare sudah masuk wishlist ti...,"[skincare, sama, bodycare, sudah, masuk, wishl..."
3,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k Diskon beli di link ini httpstcoripRFe7A...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN,225k diskon beli di link ini httpstcoriprfe7a...,225k diskon beli di link ini httpstcoriprfe7ap...,"[225k, diskon, beli, di, link, ini, httpstcori..."
4,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,LazadaID Di Lazada Ramadan Pesta Gajian aku pe...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN,lazadaid di lazada ramadan pesta gajian aku pe...,lazadaid di lazada ramadan pesta gaji aku ken ...,"[lazadaid, di, lazada, ramadan, pesta, gaji, a..."
5,2026185230848286951,Tue Feb 24 08:18:01 +0000 2026,0,saphelune_ udh gitu selesainya masih harus ski...,2026209992148488500,NaN,saphelune_,in,NaN,0,1,0,https://x.com/undefined/status/202620999214848...,1353536078687342594,NaN,saphelune_ udh gitu selesainya masih harus ski...,saphelune udh gitu selesai masih harus skincar...,"[saphelune, udh, gitu, selesai, masih, harus, ..."
6,2026207726976872844,Tue Feb 24 08:09:05 +0000 2026,3,Ciara Scar Set aku tuh punya kulit yang sensi...,2026207740239249649,https://pbs.twimg.com/media/HB6JMmhaUAA73w9.jpg,irapersa,in,NaN,0,1,1,https://x.com/undefined/status/202620774023924...,1022437026719657984,NaN,ciara scar set aku tuh punya kulit yang sensit...,ciara scar set aku tuh punya kulit yang sensit...,"[ciara, scar, set, aku, tuh, punya, kulit, yan..."
7,2026207726976872844,Tue Feb 24 08:09:01 +0000 2026,796,BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...,2026207726976872844,https://pbs.twimg.com/media/HB6JL2JbYAEjPPE.jpg,NaN,in,NaN,1,19,157,https://x.com/undefined/status/202620772697687...,1022437026719657984,NaN,beberapa combo bodycare yang paling gong 2026 ...,beberapa combo bodycare yang paling gong 2026 ...,"[beberapa, combo, bodycare, yang, paling, gong..."
8,2026119699835322640,Tue Feb 24 07:53:57 +0000 2026,0,potarisweatt apalg pas bagian bodycare butuh w...,2026203935552500091,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202620393555250...,1336009723468869635,NaN,potarisweatt apalg pas bagian bodycare butuh w...,potarisweatt apalg pas bagi bodycare butuh wak...,"[potarisweatt, apalg, pas, bagi, bodycare, but..."
9,2026176027517661268,Tue Feb 24 06:03:14 +0000 2026,0,aku suka bgt jalanjalan ke alam resikonya bawa...,2026176070509363282,https://pbs.twimg.com/media/HB5sXqQaIAAxRmW.jpg,terangremboelan,in,NaN,0,1,0,https://x.com/undefined/status/202617607050936...,1667470100914634752,NaN,aku suka bgt jalanjalan ke alam resikonya bawa...,aku suka banget jalanjalan ke alam resiko bawa...,"[aku, suka, banget, jalanjalan, ke, alam, resi..."
10,2026144267899695257,Tue Feb 24 04:03:39 +0000 2026,0,stberryorange drwhiteskincare Pas banget bodyc...,2026145978856980659,NaN,stberryorange,in,NaN,0,1,0,https://x.com/undefined/status/202614597885698...,709063820233146368,NaN,stberryorange drwhiteskincare pas banget bodyc...,stberryorange drwhiteskincare pas banget bodyc...,"[stberryorange, drwhiteskincare, pas, banget, ..."
11,2026141939331146014,Tue Feb 24 03:47:36 +0000 2026,0,selldips skincare bodycare parfum baju tanktop...,2026141939331146014,https://pbs.twimg.com/media/HB5NVWGbUAAcnZS.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202614193933114...,1847520733028896769,NaN,selldips skincare bodycare parfum baju tanktop...,selldips skincare bodycare parfum baju tanktop...,"[selldips, skincare, bodycare, parfum, baju, t..."
12,2026132112374702508,Tue Feb 24 03:08:33 +0000 2026,0,Oh My Skin PINK LOVE GLUTA SOAP sabun pencera...,2026132112374702508,https://pbs.twimg.com/media/HB5EafrasAAaHZ7.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202613211237470...,1484895347315187712,NaN,oh my skin pink love gluta soap sabun pencera...,oh my skin pink love gluta soap sabun cerah ba...,"[oh, my, skin, pink, love, gluta, soap, sabun,..."
13,2026119699835322640,Tue Feb 24 02:29:36 +0000 2026,0,potarisweatt tapi kalau pakai skincare bodycar...,2026122309690622438,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202612230969062...,1406251828417761282,NaN,potarisweatt tapi kalau pakai skincare bodycar...,potarisweatt tapi kalau pakai skincare bodycar...,"[potarisweatt, tapi, kalau, pakai, skincare, b..."
14,2026119699835322640,Tue Feb 24 02:19:14 +0000 2026,28,baru sadar klo jd cewe tuh capek pliss kudu ra...,2026119699835322640,NaN,NaN,in,NaN,2,25,0,https://x.com/undefined/status/202611969983532...,2332802611,NaN,baru sadar klo jd cewe tuh capek pliss kudu ra...,baru sadar kalau jadi cewek tuh capek pliss ha...,"[baru, sadar, kalau, jadi, cewek, tuh, capek, ..."
15,2025907789697298671,Tue Feb 24 02:02:02 +0000 2026,0,NAH cipa juga masukin L occitane sama Kerastas...,2026115369128370284,https://pbs.twimg.com/media/HB41LUtaYAAOijF.jpg,journeywithApr,in,NaN,0,0,0,https://x.com/undefined/status/202611536912837...,2402369514,NaN,nah cipa juga masukin l occitane sama kerastas...,nah cipa juga masuk l occitane sama kerastase ...,"[nah, cipa, juga, masuk, l, occitane, sama, ke..."
16,2026112464983904497,Tue Feb 24 02:01:29 +0000 2026,0,BosRQ_ skincare dan bodycare udah sekarat untu...,2026115232679313485,NaN,BosRQ_,in,NaN,0,0,0,https://x.com/undefined/status/202611523267931...,1926789679707238400,NaN,bosrq_ skincare dan bodycare udah sekarat untu...,bosrq skincare dan bodycare sudah sekarat untu...,"[bosrq, skincare, dan, bodycare, sudah, sekara..."
17,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,Bodycare abis sabun lotion sekalian beli 2 gr...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN,bodycare abis sabun lotion sekalian beli 2 gr...,bodycare habis sabun lotion sekali beli 2 grat...,"[bodycare, habis, sabun, lotion, sekali, beli,..."
18,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo Beli 2 Gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN,siapa sih yang bisa nolak promo beli 2 gratis ...,siapa sih yang bisa nolak promo beli 2 gratis ...,"[siapa, sih, yang, bisa, nolak, promo, beli, 2..."
19,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN,skincare sama bodycare udah masuk wishlist tin...,skincare sama bodycare sudah masuk wishlist ti...,"[skincare, sama, bodycare, sudah, masuk, wishl..."
20,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k Diskon beli di link ini httpstcoripRFe7A...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN,225k diskon beli di link ini httpstcoriprfe7a...,225k diskon beli di link ini httpstcoriprfe7ap...,"[225k, diskon, beli, di, link, ini, httpstcori..."
21,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,LazadaID Di Lazada Ramadan Pesta Gajian aku pe...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN,lazadaid di lazada ramadan pesta gajian aku pe...,lazadaid di lazada ramadan pesta gaji aku ken ...,"[lazadaid, di, lazada, ramadan, pesta, gaji, a..."
22,2026185230848286951,Tue Feb 24 08:18:01 +0000 2026,0,saphelune_ udh gitu selesainya masih harus ski...,2026209992148488500,NaN,saphelune_,in,NaN,0,1,0,https://x.com/undefined/status/202620999214848...,1353536078687342594,NaN,saphelune_ udh gitu selesainya masih harus ski...,saphelune udh gitu selesai masih harus skincar...,"[saphelune, udh, gitu, selesai, masih, harus, ..."
23,2026207726976872844,Tue Feb 24 08:09:05 +0000 2026,3,Ciara Scar Set aku tuh punya kulit yang sensi...,2026207740239249649,https://pbs.twimg.com/media/HB6JMmhaUAA73w9.jpg,irapersa,in,NaN,0,1,1,https://x.com/undefined/status/202620774023924...,1022437026719657984,NaN,ciara scar set aku tuh punya kulit yang sensit...,ciara scar set aku tuh punya kulit yang sensit...,"[ciara, scar, set, aku, tuh, punya, kulit, yan..."
24,2026207726976872844,Tue Feb 24 08:09:01 +0000 2026,796,BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...,2026207726976872844,https://pbs.twimg.com/media/HB6JL2JbYAEjPPE.jpg,NaN,in,NaN,1,19,157,https://x.com/undefined/status/202620772697687...,1022437026719657984,NaN,beberapa combo bodycare yang paling gong 2026 ...,beberapa combo bodycare yang paling gong 2026 ...,"[beberapa, combo, bodycare, yang, paling, gong..."
25,2026119699835322640,Tue Feb 24 07:53:57 +0000 2026,0,potarisweatt apalg pas bagian bodycare butuh w...,2026203935552500091,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202620393555250...,1336009723468869635,NaN,potarisweatt apalg pas bagian bodycare butuh w...,potarisweatt apalg pas bagi bodycare butuh wak...,"[potarisweatt, apalg, pas, bagi, bodycare, but..."
26,2026176027517661268,Tue Feb 24 06:03:14 +0000 2026,0,aku suka bgt jalanjalan ke alam resikonya bawa...,2026176070509363282,https://pbs.twimg.com/media/HB5sXqQaIAAxRmW.jpg,terangremboelan,in,NaN,0,1,0,https://x.com/undefined/status/202617607050936...,1667470100914634752,NaN,aku suka bgt jalanjalan ke alam resikonya bawa...,aku suka banget jalanjalan ke alam resiko bawa...,"[aku, suka, banget, jalanjalan, ke, alam, resi..."
27,2026144267899695257,Tue Feb 24 04:03:39 +0000 2026,0,stberryorange drwhiteskincare Pas banget bodyc...,2026145978856980659,NaN,stberryorange,in,NaN,0,1,0,https://x.com/undefined/status/202614597885698...,709063820233146368,NaN,stberryorange drwhiteskincare pas banget bodyc...,stberryorange drwhiteskincare pas banget bodyc...,"[stberryorange, drwhiteskincare, pas, banget, ..."
28,2026141939331146014,Tue Feb 24 03:47:36 +0000 2026,0,selldips skincare bodycare parfum baju tanktop...,2026141939331146014,https://pbs.twimg.com/media/HB5NVWGbUAAcnZS.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202614193933114...,1847520733028896769,NaN,selldips skincare bodycare parfum baju tanktop...,selldips skincare bodycare parfum baju tanktop...,"[selldips, skincare, bodycare, parfum, baju, t..."
29,2026132112374702508,Tue Feb 24 03:08:33 +0000 2026,0,Oh My Skin PINK LOVE GLUTA SOAP sabun pencera...,2026132112374702508,https://pbs.twimg.com/media/HB5EafrasAAaHZ7.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202613211237470...,1484895347315187712,NaN,oh my skin pink love gluta soap sabun pencera...,oh my skin pink love gluta soap sabun cerah ba...,"[oh, my, skin, pink, love, gluta, soap, sabun,..."
30,2026119699835322640,Tue Feb 24 02:29:36 +0000 2026,0,potarisweatt tapi kalau pakai skincare bodycar...,2026122309690622438,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202612230969062...,1406251828417761282,NaN,potarisweatt tapi kalau pakai skincare bodycar...,potarisweatt tapi kalau pakai skincare bodycar...,"[potarisweatt, tapi, kalau, pakai, skincare, b..."
31,2026119699835322640,Tue Feb 24 02:19:14 +0000 2026,28,baru sadar klo jd cewe tuh capek pliss kudu ra...,2026119699835322640,NaN,NaN,in,NaN,2,25,0,https://x.com/undefined/status/202611969983532...,2332802611,NaN,baru sadar klo jd cewe tuh capek pliss kudu ra...,baru sadar kalau jadi cewek tuh capek pliss ha...,"[baru, sadar, kalau, jadi, cewek, tuh, capek, ..."
32,2025907789697298671,Tue Feb 24 02:02:02 +0000 2026,0,NAH cipa juga masukin L occitane sama Kerastas...,2026115369128370284,https://pbs.twimg.com/media/HB41LUtaYAAOijF.jpg,journeywithApr,in,NaN,0,0,0,https://x.com/undefined/status/202611536912837...,2402369514,NaN,nah cipa juga masukin l occitane sama kerastas...,nah cipa juga masuk l occitane sama kerastase ...,"[nah, cipa, juga, masuk, l, occitane, sama, ke..."
33,2026112464983904497,Tue Feb 24 02:01:29 +0000 2026,0,BosRQ_ skincare dan bodycare udah sekarat untu...,2026115232679313485,NaN,BosRQ_,in,NaN,0,0,0,https://x.com/undefined/status/202611523267931...,1926789679707238400,NaN,bosrq_ skincare dan bodycare udah sekarat untu...,bosrq skincare dan bodycare sudah sekarat untu...,"[bosrq, skincare, dan, bodycare, sudah, sekara..."
34,2026285198330175691,Tue Feb 24 13:16:52 +0000 2026,0,Bodycare abis sabun lotion sekalian beli 2 gr...,2026285198330175691,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202628519833017...,1868228002225795072,NaN,bodycare abis sabun lotion sekalian beli 2 gr...,bodycare habis sabun lotion sekali beli 2 grat...,"[bodycare, habis, sabun, lotion, sekali, beli,..."
35,2026276070312563130,Tue Feb 24 12:40:36 +0000 2026,0,siapa sih yang bisa nolak promo Beli 2 Gratis ...,2026276070312563130,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202627607031256...,1909797905210490880,NaN,siapa sih yang bisa nolak promo beli 2 gratis ...,siapa sih yang bisa nolak promo beli 2 gratis ...,"[siapa, sih, yang, bisa, nolak, promo, beli, 2..."
36,2026253962266210718,Tue Feb 24 11:12:45 +0000 2026,0,skincare sama bodycare udah masuk wishlist tin...,2026253962266210718,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625396226621...,1576066390205038592,NaN,skincare sama bodycare udah masuk wishlist tin...,skincare sama bodycare sudah masuk wishlist ti...,"[skincare, sama, bodycare, sudah, masuk, wishl..."
37,2026252291360366831,Tue Feb 24 11:06:06 +0000 2026,0,225k Diskon beli di link ini httpstcoripRFe7A...,2026252291360366831,https://pbs.twimg.com/media/HB6xuHna8AAkWJ5.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202625229136036...,1991106673247961089,NaN,225k diskon beli di link ini httpstcoriprfe7a...,225k diskon beli di link ini httpstcoriprfe7ap...,"[225k, diskon, beli, di, link, ini, httpstcori..."
38,2026243388606165478,Tue Feb 24 11:01:29 +0000 2026,0,LazadaID Di Lazada Ramadan Pesta Gajian aku pe...,2026251126857961779,NaN,LazadaID,in,NaN,0,0,0,https://x.com/undefined/status/202625112685796...,1161502748,NaN,lazadaid di lazada ramadan pesta gajian aku pe...,lazadaid di lazada ramadan pesta gaji aku ken ...,"[lazadaid, di, lazada, ramadan, pesta, gaji, a..."
39,2026185230848286951,Tue Feb 24 08:18:01 +0000 2026,0,saphelune_ udh gitu selesainya masih harus ski...,2026209992148488500,NaN,saphelune_,in,NaN,0,1,0,https://x.com/undefined/status/202620999214848...,1353536078687342594,NaN,saphelune_ udh gitu selesainya masih harus ski...,saphelune udh gitu selesai masih harus skincar...,"[saphelune, udh, gitu, selesai, masih, harus, ..."
40,2026207726976872844,Tue Feb 24 08:09:05 +0000 2026,3,Ciara Scar Set aku tuh punya kulit yang sensi...,2026207740239249649,https://pbs.twimg.com/media/HB6JMmhaUAA73w9.jpg,irapersa,in,NaN,0,1,1,https://x.com/undefined/status/202620774023924...,1022437026719657984,NaN,ciara scar set aku tuh punya kulit yang sensit...,ciara scar set aku tuh punya kulit yang sensit...,"[ciara, scar, set, aku, tuh, punya, kulit, yan..."
41,2026207726976872844,Tue Feb 24 08:09:01 +0000 2026,796,BEBERAPA COMBO BODYCARE YANG PALING GONG 2026 ...,2026207726976872844,https://pbs.twimg.com/media/HB6JL2JbYAEjPPE.jpg,NaN,in,NaN,1,19,157,https://x.com/undefined/status/202620772697687...,1022437026719657984,NaN,beberapa combo bodycare yang paling gong 2026 ...,beberapa combo bodycare yang paling gong 2026 ...,"[beberapa, combo, bodycare, yang, paling, gong..."
42,2026119699835322640,Tue Feb 24 07:53:57 +0000 2026,0,potarisweatt apalg pas bagian bodycare butuh w...,2026203935552500091,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202620393555250...,1336009723468869635,NaN,potarisweatt apalg pas bagian bodycare butuh w...,potarisweatt apalg pas bagi bodycare butuh wak...,"[potarisweatt, apalg, pas, bagi, bodycare, but..."
43,2026176027517661268,Tue Feb 24 06:03:14 +0000 2026,0,aku suka bgt jalanjalan ke alam resikonya bawa...,2026176070509363282,https://pbs.twimg.com/media/HB5sXqQaIAAxRmW.jpg,terangremboelan,in,NaN,0,1,0,https://x.com/undefined/status/202617607050936...,1667470100914634752,NaN,aku suka bgt jalanjalan ke alam resikonya bawa...,aku suka banget jalanjalan ke alam resiko bawa...,"[aku, suka, banget, jalanjalan, ke, alam, resi..."
44,2026144267899695257,Tue Feb 24 04:03:39 +0000 2026,0,stberryorange drwhiteskincare Pas banget bodyc...,2026145978856980659,NaN,stberryorange,in,NaN,0,1,0,https://x.com/undefined/status/202614597885698...,709063820233146368,NaN,stberryorange drwhiteskincare pas banget bodyc...,stberryorange drwhiteskincare pas banget bodyc...,"[stberryorange, drwhiteskincare, pas, banget, ..."
45,2026141939331146014,Tue Feb 24 03:47:36 +0000 2026,0,selldips skincare bodycare parfum baju tanktop...,2026141939331146014,https://pbs.twimg.com/media/HB5NVWGbUAAcnZS.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202614193933114...,1847520733028896769,NaN,selldips skincare bodycare parfum baju tanktop...,selldips skincare bodycare parfum baju tanktop...,"[selldips, skincare, bodycare, parfum, baju, t..."
46,2026132112374702508,Tue Feb 24 03:08:33 +0000 2026,0,Oh My Skin PINK LOVE GLUTA SOAP sabun pencera...,2026132112374702508,https://pbs.twimg.com/media/HB5EafrasAAaHZ7.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202613211237470...,1484895347315187712,NaN,oh my skin pink love gluta soap sabun pencera...,oh my skin pink love gluta soap sabun cerah ba...,"[oh, my, skin, pink, love, gluta, soap, sabun,..."
47,2026119699835322640,Tue Feb 24 02:29:36 +0000 2026,0,potarisweatt tapi kalau pakai skincare bodycar...,2026122309690622438,NaN,potarisweatt,in,NaN,0,1,0,https://x.com/undefined/status/202612230969062...,1406251828417761282,NaN,potarisweatt tapi kalau pakai skincare bodycar...,potarisweatt tapi kalau pakai skincare bodycar...,"[potarisweatt, tapi, kalau, pakai, skincare, b..."
48,2026119699835322640,Tue Feb 24 02:19:14 +0000 2026,28,baru sadar klo jd cewe tuh capek pliss kudu ra...,2026119699835322640,NaN,NaN,in,NaN,2,25,0,https://x.com/undefined/status/202611969983532...,2332802611,NaN,baru sadar klo jd cewe tuh capek pliss kudu ra...,baru sadar kalau jadi cewek tuh capek pliss ha...,"[baru, sadar, kalau, jadi, cewek, tuh, capek, ..."
49,2025907789697298671,Tue Feb 24 02:02:02 +0000 2026,0,NAH cipa juga masukin L occitane sama Kerastas...,2026115369128370284,https://pbs.twimg.com/media/HB41LUtaYAAOijF.jpg,journeywithApr,in,NaN,0,0,0,https://x.com/undefined/status/202611536912837...,2402369514,NaN,nah cipa juga masukin l occitane sama kerastas...,nah cipa juga masuk l occitane sama kerastase ...,"[nah, cipa, juga, masuk, l, occitane, sama, ke..."