bahasa indonesia

In [1]:
#import library
import pandas as pd

In [2]:
# Persiapan data
data = [
    "Aku suka banget produk ini!!! 😍😍 Kualitasnya TOP banget...",
    "Pengiriman lama bgt :( padahal udah nunggu 7 hari!!!",
    "Harga 100rb tapi kualitasnya biasa aja??? 🤔",
    "Mantaaappp!!! bakal beli lagi di toko ini 💯🔥",
    "Seller ramah & fast respon, recommended!!! 👍",
    "Barang rusak!!! packaging jelek :( kecewaaa...",
    "Worth it gak sih??? Menurutku sih lumayan lah 😅",
    "Diskon 50% bikin ngiler!!! 🤩🤑",
    "Chat dibalas 2 jam kemudian... agak lama ya :/",
    "Overall oke kok!!! Cuma minus di pengiriman 🚚📦"
]

In [3]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth',None)

In [4]:
#ubah data menjadi bentuk dataframe
data_df = pd.DataFrame(data, columns=["review"])

In [5]:
#lihat 5 dataframe teratas
data_df.head()

                                                       review
0  Aku suka banget produk ini!!! 😍😍 Kualitasnya TOP banget...
1        Pengiriman lama bgt :( padahal udah nunggu 7 hari!!!
2                 Harga 100rb tapi kualitasnya biasa aja??? 🤔
3                Mantaaappp!!! bakal beli lagi di toko ini 💯🔥
4                Seller ramah & fast respon, recommended!!! 👍

In [6]:
#copy data
df = data_df.copy()
df

                                                       review
0  Aku suka banget produk ini!!! 😍😍 Kualitasnya TOP banget...
1        Pengiriman lama bgt :( padahal udah nunggu 7 hari!!!
2                 Harga 100rb tapi kualitasnya biasa aja??? 🤔
3                Mantaaappp!!! bakal beli lagi di toko ini 💯🔥
4                Seller ramah & fast respon, recommended!!! 👍
5              Barang rusak!!! packaging jelek :( kecewaaa...
6             Worth it gak sih??? Menurutku sih lumayan lah 😅
7                               Diskon 50% bikin ngiler!!! 🤩🤑
8              Chat dibalas 2 jam kemudian... agak lama ya :/
9              Overall oke kok!!! Cuma minus di pengiriman 🚚📦

In [7]:
#ubah data menjadi huruf kecil
df['review_clean'] = df['review'].str.lower()

In [8]:
df

,review,review_clean
0,Aku suka banget produk ini!!! 😍😍 Kualitasnya TOP banget...,aku suka banget produk ini!!! 😍😍 kualitasnya top banget...
1,Pengiriman lama bgt :( padahal udah nunggu 7 hari!!!,pengiriman lama bgt :( padahal udah nunggu 7 hari!!!
2,Harga 100rb tapi kualitasnya biasa aja??? 🤔,harga 100rb tapi kualitasnya biasa aja??? 🤔
3,Mantaaappp!!! bakal beli lagi di toko ini 💯🔥,mantaaappp!!! bakal beli lagi di toko ini 💯🔥
4,"Seller ramah & fast respon, recommended!!! 👍","seller ramah & fast respon, recommended!!! 👍"
5,Barang rusak!!! packaging jelek :( kecewaaa...,barang rusak!!! packaging jelek :( kecewaaa...
6,Worth it gak sih??? Menurutku sih lumayan lah 😅,worth it gak sih??? menurutku sih lumayan lah 😅
7,Diskon 50% bikin ngiler!!! 🤩🤑,diskon 50% bikin ngiler!!! 🤩🤑
8,Chat dibalas 2 jam kemudian... agak lama ya :/,chat dibalas 2 jam kemudian... agak lama ya :/
9,Overall oke kok!!! Cuma minus di pengiriman 🚚📦,overall oke kok!!! cuma minus di pengiriman 🚚📦

In [9]:
df['review_clean'].str.replace('[^\w\s]','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35156\2752707463.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['review_clean'].str.replace('[^\w\s]','',regex=True)

0    aku suka banget produk ini  kualitasnya top banget
1       pengiriman lama bgt  padahal udah nunggu 7 hari
2               harga 100rb tapi kualitasnya biasa aja
3               mantaaappp bakal beli lagi di toko ini
4                seller ramah  fast respon recommended
5                barang rusak packaging jelek  kecewaaa
6           worth it gak sih menurutku sih lumayan lah
7                               diskon 50 bikin ngiler
8             chat dibalas 2 jam kemudian agak lama ya
9             overall oke kok cuma minus di pengiriman
Name: review_clean, dtype: object

In [10]:
df['review_clean'].str.replace(r'(.)\1{2,}', r'\1',regex=True)

0    aku suka banget produk ini! 😍😍 kualitasnya top banget.
1        pengiriman lama bgt :( padahal udah nunggu 7 hari!
2                 harga 100rb tapi kualitasnya biasa aja? 🤔
3                    mantap! bakal beli lagi di toko ini 💯🔥
4                seller ramah & fast respon, recommended! 👍
5                  barang rusak! packaging jelek :( kecewa.
6             worth it gak sih? menurutku sih lumayan lah 😅
7                               diskon 50% bikin ngiler! 🤩🤑
8              chat dibalas 2 jam kemudian. agak lama ya :/
9              overall oke kok! cuma minus di pengiriman 🚚📦
Name: review_clean, dtype: object

In [11]:
df['review_clean'] = df['review_clean'].str.strip()

In [12]:
def clean_review(df, column_name):

    df['review_clean'] = df[column_name].str.lower()

    df['review_clean'] = df['review_clean'].str.strip()

    df['review_clean'] = df['review_clean'].str.replace('[^\w\s]', '', regex=True)

    df['review_clean'] = df['review_clean'].str.replace(r'(.)\1{2,}', r'\1', regex=True)

    return df

<>:7: SyntaxWarning: invalid escape sequence '\w'
<>:7: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_35156\1984791129.py:7: SyntaxWarning: invalid escape sequence '\w'
  df['review_clean'] = df['review_clean'].str.replace('[^\w\s]', '', regex=True)

In [13]:
# Jalankan fungsi
df = clean_review(df, 'review')

print(df[['review', 'review_clean']])

                                                       review  \
0  Aku suka banget produk ini!!! 😍😍 Kualitasnya TOP banget...
1        Pengiriman lama bgt :( padahal udah nunggu 7 hari!!!
2                 Harga 100rb tapi kualitasnya biasa aja??? 🤔
3                Mantaaappp!!! bakal beli lagi di toko ini 💯🔥
4                Seller ramah & fast respon, recommended!!! 👍
5              Barang rusak!!! packaging jelek :( kecewaaa...
6             Worth it gak sih??? Menurutku sih lumayan lah 😅
7                               Diskon 50% bikin ngiler!!! 🤩🤑
8              Chat dibalas 2 jam kemudian... agak lama ya :/
9              Overall oke kok!!! Cuma minus di pengiriman 🚚📦

                                         review_clean
0  aku suka banget produk ini  kualitasnya top banget
1     pengiriman lama bgt  padahal udah nunggu 7 hari
2             harga 100rb tapi kualitasnya biasa aja
3                 mantap bakal beli lagi di toko ini
4              seller ramah  fast respon recommended
5                barang rusak packaging jelek  kecewa
6         worth it gak sih menurutku sih lumayan lah
7                             diskon 50 bikin ngiler
8           chat dibalas 2 jam kemudian agak lama ya
9           overall oke kok cuma minus di pengiriman

In [14]:
#load stop word
stopwords_url = "https://raw.githubusercontent.com/datascienceid/stopwords-bahasa-indonesia/master/stopwords_id_satya.txt"
stopwords = pd.read_csv(stopwords_url, header=None)[0].tolist()
stopwords

['ada',
 'adanya',
 'adalah',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'diantaranya',
 'antara',
 'antaranya',
 'diantara',
 'apa',
 'apaan',
 'mengapa',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'atau',
 'ataukah',
 'ataupun',
 'bagai',
 'bagaikan',
 'sebagai',
 'sebagainya',
 'bagaimana',
 'bagaimanapun',
 'sebagaimana',
 'bagaimanakah',
 'bagi',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'sebaliknya',
 'banyak',
 'sebanyak',
 'beberapa',
 'seberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'sebegini',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'sebegitu',
 'belum',
 'belumlah',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'betulkah',
 'sebetulnya',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'sebisanya',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'cuma',
 'percuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'sedemikian',
 'dengan',
 'depan',
 'di',
 'dia',
 'dialah',
 'dini',
 'diri',
 'dirinya',
 'terdiri',
 'dong',
 'dulu',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'terhadap',
 'terhadapnya',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'harus',
 'haruslah',
 'harusnya',
 'seharusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'sehingga',
 'ia',
 'ialah',
 'ibarat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jangan',
 'jangankan',
 'janganlah',
 'jika',
 'jikalau',
 'juga',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'dikarenakan',
 'karena',
 'karenanya',
 'ke',
 'kecil',
 'kemudian',
 'kenapa',
 'kepada',
 'kepadanya',
 'ketika',
 'seketika',
 'khususnya',
 'kini',
 'kinilah',
 'kiranya',
 'sekiranya',
 'kita',
 'kitalah',
 'kok',
 'lagi',
 'lagian',
 'selagi',
 'lah',
 'lain',
 'lainnya',
 'melainkan',
 'selaku',
 'lalu',
 'melalui',
 'terlalu',
 'lama',
 'lamanya',
 'selama',
 'selama',
 'selamanya',
 'lebih',
 'terlebih',
 'bermacam',
 'macam',
 'semacam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masih',
 'masihkah',
 'semasih',
 'masing',
 'mau',
 'maupun',
 'semaunya',
 'memang',
 'mereka',
 'merekalah',
 'meski',
 'meskipun',
 'semula',
 'mungkin',
 'mungkinkah',
 'nah',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'oleh',
 'olehnya',
 'seorang',
 'seseorang',
 'pada',
 'padanya',
 'padahal',
 'paling',
 'sepanjang',
 'pantas',
 'sepantasnya',
 'sepantasnyalah',
 'para',
 'pasti',
 'pastilah',
 'per',
 'pernah',
 'pula',
 'pun',
 'merupakan',
 'rupanya',
 'serupa',
 'saat',
 'saatnya',
 'sesaat',
 'saja',
 'sajalah',
 'saling',
 'bersama',
 'sama',
 'sesama',
 'sambil',
 'sampai',
 'sana',
 'sangat',
 'sangatlah',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebuah',
 'tersebut',
 'tersebutlah',
 'sedang',
 'sedangkan',
 'sedikit',
 'sedikitnya',
 'segala',
 'segalanya',
 'segera',
 'sesegera',
 'sejak',
 'sejenak',
 'sekali',
 'sekalian',
 'sekalipun',
 'sesekali',
 'sekaligus',
 'sekarang',
 'sekarang',
 'sekitar',
 'sekitarnya',
 'sela',
 'selain',
 'selalu',
 'seluruh',
 'seluruhnya',
 'semakin',
 'sementara',
 'sempat',
 'semua',
 'semuanya',
 'sendiri',
 'sendirinya',
 'seolah',
 'seperti',
 'sepertinya',
 'sering',
 'seringnya',
 'serta',
 'siapa',
 'siapakah',
 'siapapun',
 'disini',
 'disinilah',
 'sini',
 'sinilah',
 'sesuatu',
 'sesuatunya',
 'suatu',
 'sesudah',
 'sesudahnya',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tak',
 'tanpa',
 'setelah',
 'telah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tertentu',
 'seterusnya',
 'tapi',
 'tetapi',
 'setiap',
 'tiap',
 'setidaknya',
 'tidak',
 'tidakkah',
 'tidaklah',
 'toh',
 'waduh',
 'wah',
 'wahai',
 'sewaktu',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakni',
 'yang']

In [15]:
#import library yang dibutuhkan
import re
import json
import requests

In [16]:
# crawl data slang
slang_url = "https://raw.githubusercontent.com/louisowen6/NLP_bahasa_resources/master/combined_slang_words.txt"
response = requests.get(slang_url)
slang_dict = json.loads(response.text)
print(slang_dict)

{'@': 'di', 'abis': 'habis', 'ad': 'ada', 'adlh': 'adalah', 'afaik': 'as far as i know', 'ahaha': 'haha', 'aj': 'saja', 'ajep-ajep': 'dunia gemerlap', 'ak': 'saya', 'akika': 'aku', 'akkoh': 'aku', 'akuwh': 'aku', 'alay': 'norak', 'alow': 'halo', 'ambilin': 'ambilkan', 'ancur': 'hancur', 'anjrit': 'anjing', 'anter': 'antar', 'ap2': 'apa-apa', 'apasih': 'apa sih', 'apes': 'sial', 'aps': 'apa', 'aq': 'saya', 'aquwh': 'aku', 'asbun': 'asal bunyi', 'aseekk': 'asyik', 'asekk': 'asyik', 'asem': 'asam', 'aspal': 'asli tetapi palsu', 'astul': 'asal tulis', 'ato': 'atau', 'au ah': 'tidak mau tahu', 'awak': 'saya', 'ay': 'sayang', 'ayank': 'sayang', 'b4': 'sebelum', 'bakalan': 'akan', 'bandes': 'bantuan desa', 'bangedh': 'banget', 'banpol': 'bantuan polisi', 'banpur': 'bantuan tempur', 'basbang': 'basi', 'bcanda': 'bercanda', 'bdg': 'bandung', 'begajulan': 'nakal', 'beliin': 'belikan', 'bencong': 'banci', 'bentar': 'sebentar', 'ber3': 'bertiga', 'beresin': 'membereskan', 'bete': 'bosan', 'beud': 'banget', 'bg': 'abang', 'bgmn': 'bagaimana', 'bgt': 'banget', 'bijimane': 'bagaimana', 'bintal': 'bimbingan mental', 'bkl': 'akan', 'bknnya': 'bukannya', 'blegug': 'bodoh', 'blh': 'boleh', 'bln': 'bulan', 'blum': 'belum', 'bnci': 'benci', 'bnran': 'yang benar', 'bodor': 'lucu', 'bokap': 'ayah', 'boker': 'buang air besar', 'bokis': 'bohong', 'boljug': 'boleh juga', 'bonek': 'bocah nekat', 'boyeh': 'boleh', 'br': 'baru', 'brg': 'bareng', 'bro': 'saudara laki-laki', 'bru': 'baru', 'bs': 'bisa', 'bsen': 'bosan', 'bt': 'buat', 'btw': 'ngomong-ngomong', 'buaya': 'tidak setia', 'bubbu': 'tidur', 'bubu': 'tidur', 'bumil': 'ibu hamil', 'bw': 'bawa', 'bwt': 'buat', 'byk': 'banyak', 'byrin': 'bayarkan', 'cabal': 'sabar', 'cadas': 'keren', 'calo': 'makelar', 'can': 'belum', 'capcus': 'pergi', 'caper': 'cari perhatian', 'ce': 'cewek', 'cekal': 'cegah tangkal', 'cemen': 'penakut', 'cengengesan': 'tertawa', 'cepet': 'cepat', 'cew': 'cewek', 'chuyunk': 'sayang', 'cimeng': 'ganja', 'cipika cipiki': 'cium pipi kanan cium pipi kiri', 'ciyh': 'sih', 'ckepp': 'cakep', 'ckp': 'cakep', 'cmiiw': "correct me if i'm wrong", 'cmpur': 'campur', 'cong': 'banci', 'conlok': 'cinta lokasi', 'cowwyy': 'maaf', 'cp': 'siapa', 'cpe': 'capek', 'cppe': 'capek', 'cucok': 'cocok', 'cuex': 'cuek', 'cumi': 'Cuma miscall', 'cups': 'culun', 'curanmor': 'pencurian kendaraan bermotor', 'curcol': 'curahan hati colongan', 'cwek': 'cewek', 'cyin': 'cinta', 'd': 'di', 'dah': 'deh', 'dapet': 'dapat', 'de': 'adik', 'dek': 'adik', 'demen': 'suka', 'deyh': 'deh', 'dgn': 'dengan', 'diancurin': 'dihancurkan', 'dimaafin': 'dimaafkan', 'dimintak': 'diminta', 'disono': 'di sana', 'dket': 'dekat', 'dkk': 'dan kawan-kawan', 'dll': 'dan lain-lain', 'dlu': 'dulu', 'dngn': 'dengan', 'dodol': 'bodoh', 'doku': 'uang', 'dongs': 'dong', 'dpt': 'dapat', 'dri': 'dari', 'drmn': 'darimana', 'drtd': 'dari tadi', 'dst': 'dan seterusnya', 'dtg': 'datang', 'duh': 'aduh', 'duren': 'durian', 'ed': 'edisi', 'egp': 'emang gue pikirin', 'eke': 'aku', 'elu': 'kamu', 'emangnya': 'memangnya', 'emng': 'memang', 'endak': 'tidak', 'enggak': 'tidak', 'envy': 'iri', 'ex': 'mantan', 'fax': 'facsimile', 'fifo': 'first in first out', 'folbek': 'follow back', 'fyi': 'sebagai informasi', 'gaada': 'tidak ada uang', 'gag': 'tidak', 'gaje': 'tidak jelas', 'gak papa': 'tidak apa-apa', 'gan': 'juragan', 'gaptek': 'gagap teknologi', 'gatek': 'gagap teknologi', 'gawe': 'kerja', 'gbs': 'tidak bisa', 'gebetan': 'orang yang disuka', 'geje': 'tidak jelas', 'gepeng': 'gelandangan dan pengemis', 'ghiy': 'lagi', 'gile': 'gila', 'gimana': 'bagaimana', 'gino': 'gigi nongol', 'githu': 'gitu', 'gj': 'tidak jelas', 'gmana': 'bagaimana', 'gn': 'begini', 'goblok': 'bodoh', 'golput': 'golongan putih', 'gowes': 'mengayuh sepeda', 'gpny': 'tidak punya', 'gr': 'gede rasa', 'gretongan': 'gratisan', 'gtau': 'tidak tahu', 'gua': 'saya', 'guoblok': 'goblok', 'gw': 'saya', 'ha': 'tertawa', 'haha': 'tertawa', 'hallow': 'halo', 'hankam': 'pertahanan dan keamanan', 'hehe': 'he', 'helo': 'halo', 'hey': 'hai', 'hlm': 'halaman', 'hny': 'hanya', 'hoax': 'isu bohong', 'hr': 'hari', 'hrus': 'harus', 'hubdar': 'perhubungan darat', 'huff': 'mengeluh', 'hum': 'rumah', 'humz': 'rumah', 'ilang': 'hilang', 'ilfil': 'tidak suka', 'imho': 'in my humble opinion', 'imoetz': 'imut', 'item': 'hitam', 'itungan': 'hitungan', 'iye': 'iya', 'ja': 'saja', 'jadiin': 'jadi', 'jaim': 'jaga image', 'jayus': 'tidak lucu', 'jdi': 'jadi', 'jem': 'jam', 'jga': 'juga', 'jgnkan': 'jangankan', 'jir': 'anjing', 'jln': 'jalan', 'jomblo': 'tidak punya pacar', 'jubir': 'juru bicara', 'jutek': 'galak', 'k': 'ke', 'kab': 'kabupaten', 'kabor': 'kabur', 'kacrut': 'kacau', 'kadiv': 'kepala divisi', 'kagak': 'tidak', 'kalo': 'kalau', 'kampret': 'sialan', 'kamtibmas': 'keamanan dan ketertiban masyarakat', 'kamuwh': 'kamu', 'kanwil': 'kantor wilayah', 'karna': 'karena', 'kasubbag': 'kepala subbagian', 'katrok': 'kampungan', 'kayanya': 'kayaknya', 'kbr': 'kabar', 'kdu': 'harus', 'kec': 'kecamatan', 'kejurnas': 'kejuaraan nasional', 'kekeuh': 'keras kepala', 'kel': 'kelurahan', 'kemaren': 'kemarin', 'kepengen': 'mau', 'kepingin': 'mau', 'kepsek': 'kepala sekolah', 'kesbang': 'kesatuan bangsa', 'kesra': 'kesejahteraan rakyat', 'ketrima': 'diterima', 'kgiatan': 'kegiatan', 'kibul': 'bohong', 'kimpoi': 'kawin', 'kl': 'kalau', 'klianz': 'kalian', 'kloter': 'kelompok terbang', 'klw': 'kalau', 'km': 'kamu', 'kmps': 'kampus', 'kmrn': 'kemarin', 'knal': 'kenal', 'knp': 'kenapa', 'kodya': 'kota madya', 'komdis': 'komisi disiplin', 'komsov': 'komunis sovyet', 'kongkow': 'kumpul bareng teman-teman', 'kopdar': 'kopi darat', 'korup': 'korupsi', 'kpn': 'kapan', 'krenz': 'keren', 'krm': 'kirim', 'kt': 'kita', 'ktmu': 'ketemu', 'ktr': 'kantor', 'kuper': 'kurang pergaulan', 'kw': 'imitasi', 'kyk': 'seperti', 'la': 'lah', 'lam': 'salam', 'lamp': 'lampiran', 'lanud': 'landasan udara', 'latgab': 'latihan gabungan', 'lebay': 'berlebihan', 'leh': 'boleh', 'lelet': 'lambat', 'lemot': 'lambat', 'lgi': 'lagi', 'lgsg': 'langsung', 'liat': 'lihat', 'litbang': 'penelitian dan pengembangan', 'lmyn': 'lumayan', 'lo': 'kamu', 'loe': 'kamu', 'lola': 'lambat berfikir', 'louph': 'cinta', 'low': 'kalau', 'lp': 'lupa', 'luber': 'langsung, umum, bebas, dan rahasia', 'luchuw': 'lucu', 'lum': 'belum', 'luthu': 'lucu', 'lwn': 'lawan', 'maacih': 'terima kasih', 'mabal': 'bolos', 'macem': 'macam', 'macih': 'masih', 'maem': 'makan', 'magabut': 'makan gaji buta', 'maho': 'homo', 'mak jang': 'kaget', 'maksain': 'memaksa', 'malem': 'malam', 'mam': 'makan', 'maneh': 'kamu', 'maniez': 'manis', 'mao': 'mau', 'masukin': 'masukkan', 'melu': 'ikut', 'mepet': 'dekat sekali', 'mgu': 'minggu', 'migas': 'minyak dan gas bumi', 'mikol': 'minuman beralkohol', 'miras': 'minuman keras', 'mlah': 'malah', 'mngkn': 'mungkin', 'mo': 'mau', 'mokad': 'mati', 'moso': 'masa', 'mpe': 'sampai', 'msk': 'masuk', 'mslh': 'masalah', 'mt': 'makan teman', 'mubes': 'musyawarah besar', 'mulu': 'melulu', 'mumpung': 'selagi', 'munas': 'musyawarah nasional', 'muntaber': 'muntah dan berak', 'musti': 'mesti', 'muupz': 'maaf', 'mw': 'now watching', 'n': 'dan', 'nanam': 'menanam', 'nanya': 'bertanya', 'napa': 'kenapa', 'napi': 'narapidana', 'napza': 'narkotika, alkohol, psikotropika, dan zat adiktif ', 'narkoba': 'narkotika, psikotropika, dan obat terlarang', 'nasgor': 'nasi goreng', 'nda': 'tidak', 'ndiri': 'sendiri', 'ne': 'ini', 'nekolin': 'neokolonialisme', 'nembak': 'menyatakan cinta', 'ngabuburit': 'menunggu berbuka puasa', 'ngaku': 'mengaku', 'ngambil': 'mengambil', 'nganggur': 'tidak punya pekerjaan', 'ngapah': 'kenapa', 'ngaret': 'terlambat', 'ngasih': 'memberikan', 'ngebandel': 'berbuat bandel', 'ngegosip': 'bergosip', 'ngeklaim': 'mengklaim', 'ngeksis': 'menjadi eksis', 'ngeles': 'berkilah', 'ngelidur': 'menggigau', 'ngerampok': 'merampok', 'ngga': 'tidak', 'ngibul': 'berbohong', 'ngiler': 'mau', 'ngiri': 'iri', 'ngisiin': 'mengisikan', 'ngmng': 'bicara', 'ngomong': 'bicara', 'ngubek2': 'mencari-cari', 'ngurus': 'mengurus', 'nie': 'ini', 'nih': 'ini', 'niyh': 'nih', 'nmr': 'nomor', 'nntn': 'nonton', 'nobar': 'nonton bareng', 'np': 'now playing', 'ntar': 'nanti', 'ntn': 'nonton', 'numpuk': 'bertumpuk', 'nutupin': 'menutupi', 'nyari': 'mencari', 'nyekar': 'menyekar', 'nyicil': 'mencicil', 'nyoblos': 'mencoblos', 'nyokap': 'ibu', 'ogah': 'tidak mau', 'ol': 'online', 'ongkir': 'ongkos kirim', 'oot': 'out of topic', 'org2': 'orang-orang', 'ortu': 'orang tua', 'otda': 'otonomi daerah', 'otw': 'on the way, sedang di jalan', 'pacal': 'pacar', 'pake': 'pakai', 'pala': 'kepala', 'pansus': 'panitia khusus', 'parpol': 'partai politik', 'pasutri': 'pasangan suami istri', 'pd': 'pada', 'pede': 'percaya diri', 'pelatnas': 'pemusatan latihan nasional', 'pemda': 'pemerintah daerah', 'pemkot': 'pemerintah kota', 'pemred': 'pemimpin redaksi', 'penjas': 'pendidikan jasmani', 'perda': 'peraturan daerah', 'perhatiin': 'perhatikan', 'pesenan': 'pesanan', 'pgang': 'pegang', 'pi': 'tapi', 'pilkada': 'pemilihan kepala daerah', 'pisan': 'sangat', 'pk': 'penjahat kelamin', 'plg': 'paling', 'pmrnth': 'pemerintah', 'polantas': 'polisi lalu lintas', 'ponpes': 'pondok pesantren', 'pp': 'pulang pergi', 'prg': 'pergi', 'prnh': 'pernah', 'psen': 'pesan', 'pst': 'pasti', 'pswt': 'pesawat', 'pw': 'posisi nyaman', 'qmu': 'kamu', 'rakor': 'rapat koordinasi', 'ranmor': 'kendaraan bermotor', 're': 'reply', 'ref': 'referensi', 'rehab': 'rehabilitasi', 'rempong': 'sulit', 'repp': 'balas', 'restik': 'reserse narkotika', 'rhs': 'rahasia', 'rmh': 'rumah', 'ru': 'baru', 'ruko': 'rumah toko', 'rusunawa': 'rumah susun sewa', 'ruz': 'terus', 'saia': 'saya', 'salting': 'salah tingkah', 'sampe': 'sampai', 'samsek': 'sama sekali', 'sapose': 'siapa', 'satpam': 'satuan pengamanan', 'sbb': 'sebagai berikut', 'sbh': 'sebuah', 'sbnrny': 'sebenarnya', 'scr': 'secara', 'sdgkn': 'sedangkan', 'sdkt': 'sedikit', 'se7': 'setuju', 'sebelas dua belas': 'mirip', 'sembako': 'sembilan bahan pokok', 'sempet': 'sempat', 'sendratari': 'seni drama tari', 'sgt': 'sangat', 'shg': 'sehingga', 'siech': 'sih', 'sikon': 'situasi dan kondisi', 'sinetron': 'sinema elektronik', 'siramin': 'siramkan', 'sj': 'saja', 'skalian': 'sekalian', 'sklh': 'sekolah', 'skt': 'sakit', 'slesai': 'selesai', 'sll': 'selalu', 'slma': 'selama', 'slsai': 'selesai', 'smpt': 'sempat', 'smw': 'semua', 'sndiri': 'sendiri', 'soljum': 'sholat jumat', 'songong': 'sombong', 'sory': 'maaf', 'sosek': 'sosial-ekonomi', 'sotoy': 'sok tahu', 'spa': 'siapa', 'sppa': 'siapa', 'spt': 'seperti', 'srtfkt': 'sertifikat', 'stiap': 'setiap', 'stlh': 'setelah', 'suk': 'masuk', 'sumpek': 'sempit', 'syg': 'sayang', 't4': 'tempat', 'tajir': 'kaya', 'tau': 'tahu', 'taw': 'tahu', 'td': 'tadi', 'tdk': 'tidak', 'teh': 'kakak perempuan', 'telat': 'terlambat', 'telmi': 'telat berpikir', 'temen': 'teman', 'tengil': 'menyebalkan', 'tepar': 'terkapar', 'tggu': 'tunggu', 'tgu': 'tunggu', 'thankz': 'terima kasih', 'thn': 'tahun', 'tilang': 'bukti pelanggaran', 'tipiwan': 'TvOne', 'tks': 'terima kasih', 'tlp': 'telepon', 'tls': 'tulis', 'tmbah': 'tambah', 'tmen2': 'teman-teman', 'tmpah': 'tumpah', 'tmpt': 'tempat', 'tngu': 'tunggu', 'tnyta': 'ternyata', 'tokai': 'tai', 'toserba': 'toko serba ada', 'tpi': 'tapi', 'trdhulu': 'terdahulu', 'trima': 'terima kasih', 'trm': 'terima', 'trs': 'terus', 'trutama': 'terutama', 'ts': 'penulis', 'tst': 'tahu sama tahu', 'ttg': 'tentang', 'tuch': 'tuh', 'tuir': 'tua', 'tw': 'tahu', 'u': 'kamu', 'ud': 'sudah', 'udah': 'sudah', 'ujg': 'ujung', 'ul': 'ulangan', 'unyu': 'lucu', 'uplot': 'unggah', 'urang': 'saya', 'usah': 'perlu', 'utk': 'untuk', 'valas': 'valuta asing', 'w/': 'dengan', 'wadir': 'wakil direktur', 'wamil': 'wajib militer', 'warkop': 'warung kopi', 'warteg': 'warung tegal', 'wat': 'buat', 'wkt': 'waktu', 'wtf': 'what the fuck', 'xixixi': 'tertawa', 'ya': 'iya', 'yap': 'iya', 'yaudah': 'ya sudah', 'yawdah': 'ya sudah', 'yg': 'yang', 'yl': 'yang lain', 'yo': 'iya', 'yowes': 'ya sudah', 'yup': 'iya', '7an': 'tujuan', 'ababil': 'abg labil', 'acc': 'accord', 'adlah': 'adalah', 'adoh': 'aduh', 'aha': 'tertawa', 'aing': 'saya', 'aja': 'saja', 'ajj': 'saja', 'aka': 'dikenal juga sebagai', 'akko': 'aku', 'akku': 'aku', 'akyu': 'aku', 'aljasa': 'asal jadi saja', 'ama': 'sama', 'ambl': 'ambil', 'anjir': 'anjing', 'ank': 'anak', 'ap': 'apa', 'apaan': 'apa', 'ape': 'apa', 'aplot': 'unggah', 'apva': 'apa', 'aqu': 'aku', 'asap': 'sesegera mungkin', 'aseek': 'asyik', 'asek': 'asyik', 'aseknya': 'asyiknya', 'asoy': 'asyik', 'astrojim': 'astagfirullahaladzim', 'ath': 'kalau begitu', 'atuh': 'kalau begitu', 'ava': 'avatar', 'aws': 'awas', 'ayang': 'sayang', 'ayok': 'ayo', 'bacot': 'banyak bicara', 'bales': 'balas', 'bangdes': 'pembangunan desa', 'bangkotan': 'tua', 'banpres': 'bantuan presiden', 'bansarkas': 'bantuan sarana kesehatan', 'bazis': 'badan amal, zakat, infak, dan sedekah', 'bcoz': 'karena', 'beb': 'sayang', 'bejibun': 'banyak', 'belom': 'belum', 'bener': 'benar', 'ber2': 'berdua', 'berdikari': 'berdiri di atas kaki sendiri', 'bet': 'banget', 'beti': 'beda tipis', 'beut': 'banget', 'bgd': 'banget', 'bgs': 'bagus', 'bhubu': 'tidur', 'bimbuluh': 'bimbingan dan penyuluhan', 'bisi': 'kalau-kalau', 'bkn': 'bukan', 'bl': 'beli', 'blg': 'bilang', 'blm': 'belum', 'bls': 'balas', 'bnchi': 'benci', 'bngung': 'bingung', 'bnyk': 'banyak', 'bohay': 'badan aduhai', 'bokep': 'porno', 'bokin': 'pacar', 'bole': 'boleh', 'bolot': 'bodoh', 'bonyok': 'ayah ibu', 'bpk': 'bapak', 'brb': 'segera kembali', 'brngkt': 'berangkat', 'brp': 'berapa', 'brur': 'saudara laki-laki', 'bsa': 'bisa', 'bsk': 'besok', 'bu_bu': 'tidur', 'bubarin': 'bubarkan', 'buber': 'buka bersama', 'bujubune': 'luar biasa', 'buser': 'buru sergap', 'bwhn': 'bawahan', 'byar': 'bayar', 'byr': 'bayar', 'c8': 'chat', 'cabut': 'pergi', 'caem': 'cakep', 'cama-cama': 'sama-sama', 'cangcut': 'celana dalam', 'cape': 'capek', 'caur': 'jelek', 'cekak': 'tidak ada uang', 'cekidot': 'coba lihat', 'cemplungin': 'cemplungkan', 'ceper': 'pendek', 'ceu': 'kakak perempuan', 'cewe': 'cewek', 'cibuk': 'sibuk', 'cin': 'cinta', 'ciye': 'cie', 'ckck': 'ck', 'clbk': 'cinta lama bersemi kembali', 'cmpr': 'campur', 'cnenk': 'senang', 'congor': 'mulut', 'cow': 'cowok', 'coz': 'karena', 'cpa': 'siapa', 'gokil': 'gila', 'gombal': 'suka merayu', 'gpl': 'tidak pakai lama', 'gpp': 'tidak apa-apa', 'gretong': 'gratis', 'gt': 'begitu', 'gtw': 'tidak tahu', 'gue': 'saya', 'guys': 'teman-teman', 'gws': 'cepat sembuh', 'haghaghag': 'tertawa', 'hakhak': 'tertawa', 'handak': 'bahan peledak', 'hansip': 'pertahanan sipil', 'hellow': 'halo', 'helow': 'halo', 'hi': 'hai', 'hlng': 'hilang', 'hnya': 'hanya', 'houm': 'rumah', 'hrs': 'harus', 'hubad': 'hubungan angkatan darat', 'hubla': 'perhubungan laut', 'huft': 'mengeluh', 'humas': 'hubungan masyarakat', 'idk': 'saya tidak tahu', 'ilfeel': 'tidak suka', 'imba': 'jago sekali', 'imoet': 'imut', 'info': 'informasi', 'itung': 'hitung', 'isengin': 'bercanda', 'iyala': 'iya lah', 'iyo': 'iya', 'jablay': 'jarang dibelai', 'jadul': 'jaman dulu', 'jancuk': 'anjing', 'jd': 'jadi', 'jdikan': 'jadikan', 'jg': 'juga', 'jgn': 'jangan', 'jijay': 'jijik', 'jkt': 'jakarta', 'jnj': 'janji', 'jth': 'jatuh', 'jurdil': 'jujur adil', 'jwb': 'jawab', 'ka': 'kakak', 'kabag': 'kepala bagian', 'kacian': 'kasihan', 'kadit': 'kepala direktorat', 'kaga': 'tidak', 'kaka': 'kakak', 'kamtib': 'keamanan dan ketertiban', 'kamuh': 'kamu', 'kamyu': 'kamu', 'kapt': 'kapten', 'kasat': 'kepala satuan', 'kasubbid': 'kepala subbidang', 'kau': 'kamu', 'kbar': 'kabar', 'kcian': 'kasihan', 'keburu': 'terlanjur', 'kedubes': 'kedutaan besar', 'kek': 'seperti', 'keknya': 'kayaknya', 'keliatan': 'kelihatan', 'keneh': 'masih', 'kepikiran': 'terpikirkan', 'kepo': 'mau tahu urusan orang', 'kere': 'tidak punya uang', 'kesian': 'kasihan', 'ketauan': 'ketahuan', 'keukeuh': 'keras kepala', 'khan': 'kan', 'kibus': 'kaki busuk', 'kk': 'kakak', 'klian': 'kalian', 'klo': 'kalau', 'kluarga': 'keluarga', 'klwrga': 'keluarga', 'kmari': 'kemari', 'kmpus': 'kampus', 'kn': 'kan', 'knl': 'kenal', 'knpa': 'kenapa', 'kog': 'kok', 'kompi': 'komputer', 'komtiong': 'komunis Tiongkok', 'konjen': 'konsulat jenderal', 'koq': 'kok', 'kpd': 'kepada', 'kptsan': 'keputusan', 'krik': 'garing', 'krn': 'karena', 'ktauan': 'ketahuan', 'ktny': 'katanya', 'kudu': 'harus', 'kuq': 'kok', 'ky': 'seperti', 'kykny': 'kayanya', 'laka': 'kecelakaan', 'lambreta': 'lambat', 'lansia': 'lanjut usia', 'lapas': 'lembaga pemasyarakatan', 'lbur': 'libur', 'lekong': 'laki-laki', 'lg': 'lagi', 'lgkp': 'lengkap', 'lht': 'lihat', 'linmas': 'perlindungan masyarakat', 'lmyan': 'lumayan', 'lngkp': 'lengkap', 'loch': 'loh', 'lol': 'tertawa', 'lom': 'belum', 'loupz': 'cinta', 'lowh': 'kamu', 'lu': 'kamu', 'luchu': 'lucu', 'luff': 'cinta', 'luph': 'cinta', 'lw': 'kamu', 'lwt': 'lewat', 'maaciw': 'terima kasih', 'mabes': 'markas besar', 'macem-macem': 'macam-macam', 'madesu': 'masa depan suram', 'maen': 'main', 'mahatma': 'maju sehat bersama', 'mak': 'ibu', 'makasih': 'terima kasih', 'malah': 'bahkan', 'malu2in': 'memalukan', 'mamz': 'makan', 'manies': 'manis', 'mantep': 'mantap', 'markus': 'makelar kasus', 'mba': 'mbak', 'mending': 'lebih baik', 'mgkn': 'mungkin', 'mhn': 'mohon', 'miker': 'minuman keras', 'milis': 'mailing list', 'mksd': 'maksud', 'mls': 'malas', 'mnt': 'minta', 'moge': 'motor gede', 'mokat': 'mati', 'mosok': 'masa', 'msh': 'masih', 'mskpn': 'meskipun', 'msng2': 'masing-masing', 'muahal': 'mahal', 'muker': 'musyawarah kerja', 'mumet': 'pusing', 'muna': 'munafik', 'munaslub': 'musyawarah nasional luar biasa', 'musda': 'musyawarah daerah', 'muup': 'maaf', 'muuv': 'maaf', 'nal': 'kenal', 'nangis': 'menangis', 'naon': 'apa', 'napol': 'narapidana politik', 'naq': 'anak', 'narsis': 'bangga pada diri sendiri', 'nax': 'anak', 'ndak': 'tidak', 'ndut': 'gendut', 'nekolim': 'neokolonialisme', 'nelfon': 'menelepon', 'ngabis2in': 'menghabiskan', 'ngakak': 'tertawa', 'ngambek': 'marah', 'ngampus': 'pergi ke kampus', 'ngantri': 'mengantri', 'ngapain': 'sedang apa', 'ngaruh': 'berpengaruh', 'ngawur': 'berbicara sembarangan', 'ngeceng': 'kumpul bareng-bareng', 'ngeh': 'sadar', 'ngekos': 'tinggal di kos', 'ngelamar': 'melamar', 'ngeliat': 'melihat', 'ngemeng': 'bicara terus-terusan', 'ngerti': 'mengerti', 'nggak': 'tidak', 'ngikut': 'ikut', 'nginep': 'menginap', 'ngisi': 'mengisi', 'ngmg': 'bicara', 'ngocol': 'lucu', 'ngomongin': 'membicarakan', 'ngumpul': 'berkumpul', 'ni': 'ini', 'nyasar': 'tersesat', 'nyariin': 'mencari', 'nyiapin': 'mempersiapkan', 'nyiram': 'menyiram', 'nyok': 'ayo', 'o/': 'oleh', 'ok': 'ok', 'priksa': 'periksa', 'pro': 'profesional', 'psn': 'pesan', 'psti': 'pasti', 'puanas': 'panas', 'qmo': 'kamu', 'qt': 'kita', 'rame': 'ramai', 'raskin': 'rakyat miskin', 'red': 'redaksi', 'reg': 'register', 'rejeki': 'rezeki', 'renstra': 'rencana strategis', 'reskrim': 'reserse kriminal', 'sni': 'sini', 'somse': 'sombong sekali', 'sorry': 'maaf', 'sosbud': 'sosial-budaya', 'sospol': 'sosial-politik', 'sowry': 'maaf', 'spd': 'sepeda', 'sprti': 'seperti', 'spy': 'supaya', 'stelah': 'setelah', 'subbag': 'subbagian', 'sumbangin': 'sumbangkan', 'sy': 'saya', 'syp': 'siapa', 'tabanas': 'tabungan pembangunan nasional', 'tar': 'nanti', 'taun': 'tahun', 'tawh': 'tahu', 'tdi': 'tadi', 'te2p': 'tetap', 'tekor': 'rugi', 'telkom': 'telekomunikasi', 'telp': 'telepon', 'temen2': 'teman-teman', 'tengok': 'menjenguk', 'terbitin': 'terbitkan', 'tgl': 'tanggal', 'thanks': 'terima kasih', 'thd': 'terhadap', 'thx': 'terima kasih', 'tipi': 'TV', 'tkg': 'tukang', 'tll': 'terlalu', 'tlpn': 'telepon', 'tman': 'teman', 'tmbh': 'tambah', 'tmn2': 'teman-teman', 'tmph': 'tumpah', 'tnda': 'tanda', 'tnh': 'tanah', 'togel': 'toto gelap', 'tp': 'tapi', 'tq': 'terima kasih', 'trgntg': 'tergantung', 'trims': 'terima kasih', 'cb': 'coba', 'y': 'ya', 'munfik': 'munafik', 'reklamuk': 'reklamasi', 'sma': 'sama', 'tren': 'trend', 'ngehe': 'kesal', 'mz': 'mas', 'analisise': 'analisis', 'sadaar': 'sadar', 'sept': 'september', 'nmenarik': 'menarik', 'zonk': 'bodoh'

In [17]:
#install sastrawi untuk bahasa indonesia
!pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
#import library sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

In [19]:
#using sastrawi
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [20]:
def clean_text(text):

    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'(.)\1{2,}', r'\1', text)
    words = text.split()

    # normalisasi slang
    words = [slang_dict[word] if word in slang_dict else word for word in words]


    text = " ".join(words)

    # stemming
    text = stemmer.stem(text)

    return text

In [21]:
# ==============================
# 8. Jalankan Pipeline
# ==============================
df['clean_review'] = df['review'].apply(clean_text)

print(df[['review', 'clean_review']])

                                                       review  \
0  Aku suka banget produk ini!!! 😍😍 Kualitasnya TOP banget...
1        Pengiriman lama bgt :( padahal udah nunggu 7 hari!!!
2                 Harga 100rb tapi kualitasnya biasa aja??? 🤔
3                Mantaaappp!!! bakal beli lagi di toko ini 💯🔥
4                Seller ramah & fast respon, recommended!!! 👍
5              Barang rusak!!! packaging jelek :( kecewaaa...
6             Worth it gak sih??? Menurutku sih lumayan lah 😅
7                               Diskon 50% bikin ngiler!!! 🤩🤑
8              Chat dibalas 2 jam kemudian... agak lama ya :/
9              Overall oke kok!!! Cuma minus di pengiriman 🚚📦

                                     clean_review
0  aku suka banget produk ini kualitas top banget
1   kirim lama banget padahal sudah nunggu 7 hari
2            harga 100rb tapi kualitas biasa saja
3              mantap bakal beli lagi di toko ini
4            seller ramah fast respon recommended
5             barang rusak packaging jelek kecewa
6          worth it gak sih turut sih lumayan lah
7                             diskon 50 bikin mau
8         chat balas 2 jam kemudian agak lama iya
9             overall oke kok cuma minus di kirim

In [22]:
import spacy
nlp = spacy.blank("id")  # tokenizer saja

def spacy_tokenize(text):
    doc = nlp(text)
    return [token.text for token in doc]

df['tokens'] = df['clean_review'].apply(spacy_tokenize)

In [23]:
df

,review,review_clean,clean_review,tokens
0,Aku suka banget produk ini!!! 😍😍 Kualitasnya TOP banget...,aku suka banget produk ini kualitasnya top banget,aku suka banget produk ini kualitas top banget,"[aku, suka, banget, produk, ini, kualitas, top, banget]"
1,Pengiriman lama bgt :( padahal udah nunggu 7 hari!!!,pengiriman lama bgt padahal udah nunggu 7 hari,kirim lama banget padahal sudah nunggu 7 hari,"[kirim, lama, banget, padahal, sudah, nunggu, 7, hari]"
2,Harga 100rb tapi kualitasnya biasa aja??? 🤔,harga 100rb tapi kualitasnya biasa aja,harga 100rb tapi kualitas biasa saja,"[harga, 100, rb, tapi, kualitas, biasa, saja]"
3,Mantaaappp!!! bakal beli lagi di toko ini 💯🔥,mantap bakal beli lagi di toko ini,mantap bakal beli lagi di toko ini,"[mantap, bakal, beli, lagi, di, toko, ini]"
4,"Seller ramah & fast respon, recommended!!! 👍",seller ramah fast respon recommended,seller ramah fast respon recommended,"[seller, ramah, fast, respon, recommended]"
5,Barang rusak!!! packaging jelek :( kecewaaa...,barang rusak packaging jelek kecewa,barang rusak packaging jelek kecewa,"[barang, rusak, packaging, jelek, kecewa]"
6,Worth it gak sih??? Menurutku sih lumayan lah 😅,worth it gak sih menurutku sih lumayan lah,worth it gak sih turut sih lumayan lah,"[worth, it, gak, sih, turut, sih, lumayan, lah]"
7,Diskon 50% bikin ngiler!!! 🤩🤑,diskon 50 bikin ngiler,diskon 50 bikin mau,"[diskon, 50, bikin, mau]"
8,Chat dibalas 2 jam kemudian... agak lama ya :/,chat dibalas 2 jam kemudian agak lama ya,chat balas 2 jam kemudian agak lama iya,"[chat, balas, 2, jam, kemudian, agak, lama, iya]"
9,Overall oke kok!!! Cuma minus di pengiriman 🚚📦,overall oke kok cuma minus di pengiriman,overall oke kok cuma minus di kirim,"[overall, oke, kok, cuma, minus, di, kirim]"