In [5]:
name = "John Doe" #string
age = 90 #integer
height = 1.75 #float
weight = 70.5 #float
id_student = True #boolean

Tipe Data Collection

In [7]:
#lIST mutable bisa diubah-ubah isinya hapus, tambah, ganti
friends = ["Alice", "Bob", "Charlie", "David", "Eve"]  #didalem sini bisa diisi dengan berbagai tipe data
variabel_with_list = [name, age, height, weight, id_student, friends] #bisa juga dimasukin ke dalam list

In [8]:
variabel_with_list

['John Doe', 90, 1.75, 70.5, True, ['Alice', 'Bob', 'Charlie', 'David', 'Eve']]

In [9]:
variabel_with_list.append("NLP")

In [10]:
variabel_with_list

['John Doe',
 90,
 1.75,
 70.5,
 True,
 ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
 'NLP']

In [11]:
help(variabel_with_list)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |
 |  Built-in mutable sequence.
 |
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, index, /)
 |      Return self[index].
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __reversed__(self, /)
 |      Return a reverse iterator over the list.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __setitem__(self, key, value, /)
 |      Set self[key] to value.
 |
 |  __sizeof__(self, /)
 |      Return the size of the list in memory, in bytes.
 |
 |  append(self, object, /)
 |      Append object to the end of the list.
 |
 |  clear(self, /)
 |      Remove all items from list.
 |
 |  copy(self, /)
 |      Return a shallow copy of the list.
 |
 |  count(self, value, /)
 |      Return number of occurrences of value.
 |
 |  extend(self, iterable, /)
 |      Extend list by appending elements from the iterable.
 |
 |  index(self, value, start=0, stop=9223372036854775807, /)
 |      Return first index of value.
 |
 |      Raises ValueError if the value is not present.
 |
 |  insert(self, index, object, /)
 |      Insert object before index.
 |
 |  pop(self, index=-1, /)
 |      Remove and return item at index (default last).
 |
 |      Raises IndexError if list is empty or index is out of range.
 |
 |  remove(self, value, /)
 |      Remove first occurrence of value.
 |
 |      Raises ValueError if the value is not present.
 |
 |  reverse(self, /)
 |      Reverse *IN PLACE*.
 |
 |  sort(self, /, *, key=None, reverse=False)
 |      Sort the list in ascending order and return None.
 |
 |      The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
 |      order of two equal elements is maintained).
 |
 |      If a key function is given, apply it once to each list item and sort them,
 |      ascending or descending, according to their function values.
 |
 |      The reverse flag can be set to sort in descending order.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  __class_getitem__(object, /)
 |      See PEP 585
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __hash__ = None

In [12]:
#TUPLE immutable tidak bisa diubah-ubah isinya
friends

['Alice', 'Bob', 'Charlie', 'David', 'Eve']

In [13]:
friends[0]

'Alice'

In [14]:
#DICTIONARY mutable bisa diubah-ubah isinya hapus, tambah, ganti
my_self = {
    "name": "John Doe",
    "age": 90,
    "height": 1.75,
}

In [15]:
my_self.keys()

dict_keys(['name', 'age', 'height'])

Peluang/Looping

In [16]:
for z in friends:
    print(z)

Alice
Bob
Charlie
David
Eve

In [17]:
#peluang dengan while
index = 0
while index < len(friends):
    print(friends[index])
    index += 1

Alice
Bob
Charlie
David
Eve

Function (fungsi)

In [2]:
def introduction(name, age, height):
    print(name)
    print(age)
    print(height)

In [3]:
def kali(x):
    return 7*x

In [4]:
result = kali(5)
print(result)

35

In [19]:
introduction("oryza", 20, 165)

oryza
20
165

conditioning

In [25]:
number = 2

In [26]:
if number%2 == 0:
    print("hore")
elif number%2 == 1:
    print("ganjil")
else :
    print("error")

hore

In [29]:
number = 7

In [30]:
if number%2 == 0:
    print("hore")
elif number%2 == 1:
    print("ganjil")
else :
    print("error")

ganjil

In [31]:
number = "NLP"

In [32]:
class Animal():
    def __init__(self, name):
        self.name = name
    def introduction(self):
        return(f"{self.name} is an animal")

In [33]:
Animal = Animal("Dog")

In [38]:
Animal.introduction()

'Dog is an animal'

In [50]:
#install google play scrapper
!pip install google-play-scraper

Requirement already satisfied: google-play-scraper in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (1.2.7)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [52]:
#import library
from google_play_scraper import reviews, Sort
import pandas as pd

In [53]:
result, continuation_token = reviews(
    'jp.konami.pesam',   # ganti dengan app id
    lang='en',              # ganti dengan bahasa
    # country='id',           # ganti dengan negara
    sort=Sort.NEWEST,       # review terbaru
    count=100              # jumlah review
)

In [54]:
#ubah jadi bentuk dataframe
result_df = pd.DataFrame(result)
result_df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8dbbc470-3fd1-4ec0-a2e6-6d6eca637a82,asif Official,https://play-lh.googleusercontent.com/a-/ALV-UjXd-gFgDXw5h2At7G7s0pSI27bGu__Jg41au8yu1-km24B9eARF,Good But........... I Need Ronaldo & Nymar🥲,5,0,10.3.0,2026-03-01 14:52:47,None,None,10.3.0
1,6f740e22-9992-4fe0-b4e7-930f2dbf6ed1,Iskandar Juraimi,https://play-lh.googleusercontent.com/a/ACg8ocI4r8hAiDb9XFNDxDhVwAVwYDq1MCueosv55Z3_wHLVIkFk4w=mo,it is better then the fc mobile,4,0,10.3.0,2026-03-01 14:43:53,None,None,10.3.0
2,ef058e06-d0ba-4750-94af-6689bdb8967e,Erick John,https://play-lh.googleusercontent.com/a/ACg8ocKD5AoRTMEczd4IqhcGJf9zX_cfG84eeHwQ-I81jQMBaiR8lg=mo,I think Ronaldo 110 should now come,5,0,10.3.0,2026-03-01 14:43:23,None,None,10.3.0
3,b40bcb87-96de-4739-83d3-b08bd2f52f68,Kelvin Gichuki,https://play-lh.googleusercontent.com/a-/ALV-UjUH1AYg1aX_BMFXkEMnkDTW1EGXsFXKbjmyCGwo9nM5rDQHW_M,best experience,4,0,10.3.0,2026-03-01 14:43:00,None,None,10.3.0
4,0d9d1cb7-c830-4157-ac6c-51e25ceac8c8,farzeenvengara,https://play-lh.googleusercontent.com/a/ACg8ocLH26A-mK2oK08wdHvk2KsrLsks2kJjXtlVIN4m-1KYEZljnQ=mo,evrithing all so good game my opinion,5,0,10.3.0,2026-03-01 14:42:48,None,None,10.3.0
...,...,...,...,...,...,...,...,...,...,...,...
95,962664a7-568c-447b-8c4a-0c0d8f3c91ab,Otf Palampa,https://play-lh.googleusercontent.com/a/ACg8ocJqPks5Byd7jKSrRFAkZQOk8gh1xUMs1UVB-bS8cg99Bjq6KQ=mo,nice to play,5,0,10.3.0,2026-03-01 10:49:22,None,None,10.3.0
96,eb5899d0-1e4e-40b4-a444-fd767c2425f8,Daniel kwaku newel Oppong,https://play-lh.googleusercontent.com/a/ACg8ocIkkje9GxRhII4ueVN6HfwHU10odTJzGL4Vwh1k82dzQZwmuA=mo,"Efootball company, work on this issue for us. For the goalkeeper, it must be cleaansheet, not goals, please",5,0,10.3.0,2026-03-01 10:47:43,None,None,10.3.0
97,a74fc830-9d12-4487-991a-dd5538727ba4,Zenab,https://play-lh.googleusercontent.com/a/ACg8ocLpaT6oh4qIHq7HLNYYWSIKk0FyDRI6gIGUyqFBva_mZ3yYhw=mo,eFootball is the fastest and smoothest football game ever and it is also play simply,5,0,None,2026-03-01 10:43:54,None,None,None
98,71b4fd91-ae56-47ff-bb60-e8b16577d839,Rina Datsa,https://play-lh.googleusercontent.com/a/ACg8ocJG775fZWRjGiw-c_gJT7Io9z_tI03eGx-_ZMD6b1F1LJ0tXw=mo,indeed one of the 👌,5,0,None,2026-03-01 10:41:26,None,None,None
99,a85d43e5-a99c-4040-9a52-221efd303f1b,Mamata Shrestha,https://play-lh.googleusercontent.com/a/ACg8ocKCEWAT3xzVpBfM105GSTUjc4Q2rVYVOJL6o-hNAOLtunQecg=mo,this game is scripted don't play this game this game is too bad fc better,1,0,10.3.0,2026-03-01 10:39:59,None,None,10.3.0

In [55]:
df = result_df.copy()
df

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8dbbc470-3fd1-4ec0-a2e6-6d6eca637a82,asif Official,https://play-lh.googleusercontent.com/a-/ALV-UjXd-gFgDXw5h2At7G7s0pSI27bGu__Jg41au8yu1-km24B9eARF,Good But........... I Need Ronaldo & Nymar🥲,5,0,10.3.0,2026-03-01 14:52:47,None,None,10.3.0
1,6f740e22-9992-4fe0-b4e7-930f2dbf6ed1,Iskandar Juraimi,https://play-lh.googleusercontent.com/a/ACg8ocI4r8hAiDb9XFNDxDhVwAVwYDq1MCueosv55Z3_wHLVIkFk4w=mo,it is better then the fc mobile,4,0,10.3.0,2026-03-01 14:43:53,None,None,10.3.0
2,ef058e06-d0ba-4750-94af-6689bdb8967e,Erick John,https://play-lh.googleusercontent.com/a/ACg8ocKD5AoRTMEczd4IqhcGJf9zX_cfG84eeHwQ-I81jQMBaiR8lg=mo,I think Ronaldo 110 should now come,5,0,10.3.0,2026-03-01 14:43:23,None,None,10.3.0
3,b40bcb87-96de-4739-83d3-b08bd2f52f68,Kelvin Gichuki,https://play-lh.googleusercontent.com/a-/ALV-UjUH1AYg1aX_BMFXkEMnkDTW1EGXsFXKbjmyCGwo9nM5rDQHW_M,best experience,4,0,10.3.0,2026-03-01 14:43:00,None,None,10.3.0
4,0d9d1cb7-c830-4157-ac6c-51e25ceac8c8,farzeenvengara,https://play-lh.googleusercontent.com/a/ACg8ocLH26A-mK2oK08wdHvk2KsrLsks2kJjXtlVIN4m-1KYEZljnQ=mo,evrithing all so good game my opinion,5,0,10.3.0,2026-03-01 14:42:48,None,None,10.3.0
...,...,...,...,...,...,...,...,...,...,...,...
95,962664a7-568c-447b-8c4a-0c0d8f3c91ab,Otf Palampa,https://play-lh.googleusercontent.com/a/ACg8ocJqPks5Byd7jKSrRFAkZQOk8gh1xUMs1UVB-bS8cg99Bjq6KQ=mo,nice to play,5,0,10.3.0,2026-03-01 10:49:22,None,None,10.3.0
96,eb5899d0-1e4e-40b4-a444-fd767c2425f8,Daniel kwaku newel Oppong,https://play-lh.googleusercontent.com/a/ACg8ocIkkje9GxRhII4ueVN6HfwHU10odTJzGL4Vwh1k82dzQZwmuA=mo,"Efootball company, work on this issue for us. For the goalkeeper, it must be cleaansheet, not goals, please",5,0,10.3.0,2026-03-01 10:47:43,None,None,10.3.0
97,a74fc830-9d12-4487-991a-dd5538727ba4,Zenab,https://play-lh.googleusercontent.com/a/ACg8ocLpaT6oh4qIHq7HLNYYWSIKk0FyDRI6gIGUyqFBva_mZ3yYhw=mo,eFootball is the fastest and smoothest football game ever and it is also play simply,5,0,None,2026-03-01 10:43:54,None,None,None
98,71b4fd91-ae56-47ff-bb60-e8b16577d839,Rina Datsa,https://play-lh.googleusercontent.com/a/ACg8ocJG775fZWRjGiw-c_gJT7Io9z_tI03eGx-_ZMD6b1F1LJ0tXw=mo,indeed one of the 👌,5,0,None,2026-03-01 10:41:26,None,None,None
99,a85d43e5-a99c-4040-9a52-221efd303f1b,Mamata Shrestha,https://play-lh.googleusercontent.com/a/ACg8ocKCEWAT3xzVpBfM105GSTUjc4Q2rVYVOJL6o-hNAOLtunQecg=mo,this game is scripted don't play this game this game is too bad fc better,1,0,10.3.0,2026-03-01 10:39:59,None,None,10.3.0

In [56]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth', None)

In [57]:
#lihat kolom konten
df['content'].head(50)

0                                                                                                                                                                                                                                                                                                                                      Good But........... I Need Ronaldo & Nymar🥲
1                                                                                                                                                                                                                                                                                                                                                  it is better then the fc mobile
2                                                                                                                                                                                                                                                                                                                                              I think Ronaldo 110 should now come
3                                                                                                                                                                                                                                                                                                                                                                  best experience
4                                                                                                                                                                                                                                                                                                                                            evrithing all so good game my opinion
5                                                                                                                                               I love the game it make me happy but one issues is when I want to use my coins to spin player they always give me the the wrong player and I am from Japan I was born in Japan Konami please give me good players that when I spin
6                                                                                                                                                                                                                                                                                                                                                                       scam packs
7                                                                                                                                                                                                                                                                      stupid game,someone using cheat,so stupid please update your system bro stupi bro stupid so so so so stupid
8                                                                                                                                                                                                                                                                                                                                                             all I can say is wow
9                                                                                                                                                                                                                                                                                                                    game is good but to play in infinix have poor vissión graphic
10                                                                                                                                                                                                                                                                              this game was excellent record but some things are disturbing like the unstable server ,game glicz
11                                                                                                                                                                                                                                                                       im giving 0 rating this game because i cant play this game in my device poco c31 64gb ram please fix that
12                                                                                                                                                                                                                                                                                                                                                          is ok just try and see
13                                                                                                                                                                                                                                                                                                                                   Konami bokachoda rendir chele from Bangladesh
14                                                                                                                                                                                                                                                                                                       konami tor ma ke chudi sala suorer bacha tor make ulto kore from Pakistan
15                                                                                                                                                                                                                                                                                                                                                                 SUPER eFOOTBAll
16                                                                                                                                                                                                                                                                                                                                                                      e football
17                                                                                                                                                                                                                                                                                    very good game. yayayayaya I like it. it's Enjoyable wow majedaar majhdaar lalaalalalalalaal
18                                                                                                                                                                                                                                                                                                                                                                    nice game 🎯👍
19                                                                                                                                                                                                                                                                                                                                                                         love it
20                                                                                                                                                                                                                        Sincerely speaking , konami remove smart assist from your game , simply the game promotes cheating in matches with opponents not playing fair and square
21    This game has become completely pay-to-win. For almost 11 months never received a single Epic or Big Time card, while paid players easily build top squads. Old Epic cards were even downgraded, which feels unfair and disrespectful. Weekly rewards are too low to matter, and gameplay often feels scripted. Skill no longer matters—only money does. Very disappointing.
22                                                                                                                                                                                                                                                                                                                             The game is good but the server is having a problem
23                                                                                                                                                                                                                                                                                                                                                         LOVE YOU TOO SWEETHEART
24                                                                                                                                                                                                                                                                                                                                                                     freestyle!!
25                                                                                                                                                                                                                                                                                                                                                                    this is nice
26                                                                                                                                                                                                                                                                                                    I hated this app because I tried to download it when it reaches 80% it stops
27                                                                                                                                                                                                                                                                                                                                                        just so perfect 💯💯❤️❤️🥳🥰
28                                                                                                                                                                                                                                                                                                                                                   voice ko on karna update karo
29                                                                                                                                                                                                                                                                                                                                                   supporting ai not the players
30                                                                                                                                                                                                                                                                                                                      I've been playing this game for 4 years now this game is 💩
31                                                                                                                                                                                                                                                                                                                                      a good experience with e football,try it❤️
32                                                                                                                                                                                                                                                                                                it is a good game with brilliant graphics i really love 💕💕 the game very much it
33                                                                                                                                                                                                                                                                                                               this is wondorful and exelent most topast football game the world
34                                                                                                                                                                                                                                                                                                                                                                            good
35                                                                                                                                                                                                                                                                                                                                CABDIQADIR ROOBLR MAXAMUUS MAREXAN COLOW SHAMAKE
36                                                                                                                                                                                                                                                                                                                                                                      game rusak
37                                                                                                                                                                                                                                                                                                                  نريد نسخة لايت للهواتف الضعيفة و ما يحدث في division غير مقبول
38                                                                                                                                                                                                                                                                                                                          why always unfinished game when I play with my friend?
39                                                                                                                                                                                                                                                                                    It's a good game is 👍, it's just that you need to show us how to do some dribbles and skills
40                    game anj, pencarian lawan nya ga setara bbi rating tim gw 3035 ketemu lawan nya 3197 anj udah juga smart assist nya dongo bbi gw shooting udah pas tiang dekat malah nendang nya ketilang jauh anj jadinya ga gol apa lagi gara gara smart assist pemainku jadi lama nendang nya. mohon segera perbaiki lah Konami soal pencarian lawan dan smart assist nya
41                                                                                                                                                                                                                                                                                                                                        efootball is the best unlike fc mobile .
42                                                                                                                                                                                                                                                                                                                                                           you want to reduce GB
43                                                                                                                                                                                                                                                                                                                                                                        so fun 😊
44                                                                                                                                                                                                                                                                                                                                                                  Very nice game
45                                                                                                                                         hey konami, please fix lagging issues while playing pvp/division. I encountered many lagging even though I'm using WiFi already. please fix your server asap. I'm done with this game if you guys aren't doing well with server issues.
46                                                                                                                                                                                                                                                                                                                                                                       very nice
47                                                                                                                                                                                                                                                                                                                                                                  Best game ever
48                                                                                                                                                                                                                                                                                                                                                                            best
49                                                                                                                                                                                                                                                                                                               This game is so nice 🙂👍 I can take a hole day playing this game 🎮
Name: content, dtype: object

In [46]:
#masukan kolom content ke dalam variabel baru
data_cleaning = df['content']
data_cleaning.head(30)

0                                                                                                                                                                                                                                                                                                                                      Good But........... I Need Ronaldo & Nymar🥲
1                                                                                                                                                                                                                                                                                                                                                  it is better then the fc mobile
2                                                                                                                                                                                                                                                                                                                                              I think Ronaldo 110 should now come
3                                                                                                                                                                                                                                                                                                                                                                  best experience
4                                                                                                                                                                                                                                                                                                                                            evrithing all so good game my opinion
5                                                                                                                                               I love the game it make me happy but one issues is when I want to use my coins to spin player they always give me the the wrong player and I am from Japan I was born in Japan Konami please give me good players that when I spin
6                                                                                                                                                                                                                                                                                                                                                                       scam packs
7                                                                                                                                                                                                                                                                      stupid game,someone using cheat,so stupid please update your system bro stupi bro stupid so so so so stupid
8                                                                                                                                                                                                                                                                                                                                                             all I can say is wow
9                                                                                                                                                                                                                                                                                                                    game is good but to play in infinix have poor vissión graphic
10                                                                                                                                                                                                                                                                              this game was excellent record but some things are disturbing like the unstable server ,game glicz
11                                                                                                                                                                                                                                                                       im giving 0 rating this game because i cant play this game in my device poco c31 64gb ram please fix that
12                                                                                                                                                                                                                                                                                                                                                          is ok just try and see
13                                                                                                                                                                                                                                                                                                                                   Konami bokachoda rendir chele from Bangladesh
14                                                                                                                                                                                                                                                                                                       konami tor ma ke chudi sala suorer bacha tor make ulto kore from Pakistan
15                                                                                                                                                                                                                                                                                                                                                                 SUPER eFOOTBAll
16                                                                                                                                                                                                                                                                                                                                                                      e football
17                                                                                                                                                                                                                                                                                    very good game. yayayayaya I like it. it's Enjoyable wow majedaar majhdaar lalaalalalalalaal
18                                                                                                                                                                                                                                                                                                                                                                    nice game 🎯👍
19                                                                                                                                                                                                                                                                                                                                                                         love it
20                                                                                                                                                                                                                        Sincerely speaking , konami remove smart assist from your game , simply the game promotes cheating in matches with opponents not playing fair and square
21    This game has become completely pay-to-win. For almost 11 months never received a single Epic or Big Time card, while paid players easily build top squads. Old Epic cards were even downgraded, which feels unfair and disrespectful. Weekly rewards are too low to matter, and gameplay often feels scripted. Skill no longer matters—only money does. Very disappointing.
22                                                                                                                                                                                                                                                                                                                             The game is good but the server is having a problem
23                                                                                                                                                                                                                                                                                                                                                         LOVE YOU TOO SWEETHEART
24                                                                                                                                                                                                                                                                                                                                                                     freestyle!!
25                                                                                                                                                                                                                                                                                                                                                                    this is nice
26                                                                                                                                                                                                                                                                                                    I hated this app because I tried to download it when it reaches 80% it stops
27                                                                                                                                                                                                                                                                                                                                                        just so perfect 💯💯❤️❤️🥳🥰
28                                                                                                                                                                                                                                                                                                                                                   voice ko on karna update karo
29                                                                                                                                                                                                                                                                                                                                                   supporting ai not the players
Name: content, dtype: object

In [58]:
df['content_clean'] = df['content'].str.lower()
df['content_clean'].head(50)

0                                                                                                                                                                                                                                                                                                                                      good but........... i need ronaldo & nymar🥲
1                                                                                                                                                                                                                                                                                                                                                  it is better then the fc mobile
2                                                                                                                                                                                                                                                                                                                                              i think ronaldo 110 should now come
3                                                                                                                                                                                                                                                                                                                                                                  best experience
4                                                                                                                                                                                                                                                                                                                                            evrithing all so good game my opinion
5                                                                                                                                               i love the game it make me happy but one issues is when i want to use my coins to spin player they always give me the the wrong player and i am from japan i was born in japan konami please give me good players that when i spin
6                                                                                                                                                                                                                                                                                                                                                                       scam packs
7                                                                                                                                                                                                                                                                      stupid game,someone using cheat,so stupid please update your system bro stupi bro stupid so so so so stupid
8                                                                                                                                                                                                                                                                                                                                                             all i can say is wow
9                                                                                                                                                                                                                                                                                                                    game is good but to play in infinix have poor vissión graphic
10                                                                                                                                                                                                                                                                              this game was excellent record but some things are disturbing like the unstable server ,game glicz
11                                                                                                                                                                                                                                                                       im giving 0 rating this game because i cant play this game in my device poco c31 64gb ram please fix that
12                                                                                                                                                                                                                                                                                                                                                          is ok just try and see
13                                                                                                                                                                                                                                                                                                                                   konami bokachoda rendir chele from bangladesh
14                                                                                                                                                                                                                                                                                                       konami tor ma ke chudi sala suorer bacha tor make ulto kore from pakistan
15                                                                                                                                                                                                                                                                                                                                                                 super efootball
16                                                                                                                                                                                                                                                                                                                                                                      e football
17                                                                                                                                                                                                                                                                                    very good game. yayayayaya i like it. it's enjoyable wow majedaar majhdaar lalaalalalalalaal
18                                                                                                                                                                                                                                                                                                                                                                    nice game 🎯👍
19                                                                                                                                                                                                                                                                                                                                                                         love it
20                                                                                                                                                                                                                        sincerely speaking , konami remove smart assist from your game , simply the game promotes cheating in matches with opponents not playing fair and square
21    this game has become completely pay-to-win. for almost 11 months never received a single epic or big time card, while paid players easily build top squads. old epic cards were even downgraded, which feels unfair and disrespectful. weekly rewards are too low to matter, and gameplay often feels scripted. skill no longer matters—only money does. very disappointing.
22                                                                                                                                                                                                                                                                                                                             the game is good but the server is having a problem
23                                                                                                                                                                                                                                                                                                                                                         love you too sweetheart
24                                                                                                                                                                                                                                                                                                                                                                     freestyle!!
25                                                                                                                                                                                                                                                                                                                                                                    this is nice
26                                                                                                                                                                                                                                                                                                    i hated this app because i tried to download it when it reaches 80% it stops
27                                                                                                                                                                                                                                                                                                                                                        just so perfect 💯💯❤️❤️🥳🥰
28                                                                                                                                                                                                                                                                                                                                                   voice ko on karna update karo
29                                                                                                                                                                                                                                                                                                                                                   supporting ai not the players
30                                                                                                                                                                                                                                                                                                                      i've been playing this game for 4 years now this game is 💩
31                                                                                                                                                                                                                                                                                                                                      a good experience with e football,try it❤️
32                                                                                                                                                                                                                                                                                                it is a good game with brilliant graphics i really love 💕💕 the game very much it
33                                                                                                                                                                                                                                                                                                               this is wondorful and exelent most topast football game the world
34                                                                                                                                                                                                                                                                                                                                                                            good
35                                                                                                                                                                                                                                                                                                                                cabdiqadir rooblr maxamuus marexan colow shamake
36                                                                                                                                                                                                                                                                                                                                                                      game rusak
37                                                                                                                                                                                                                                                                                                                  نريد نسخة لايت للهواتف الضعيفة و ما يحدث في division غير مقبول
38                                                                                                                                                                                                                                                                                                                          why always unfinished game when i play with my friend?
39                                                                                                                                                                                                                                                                                    it's a good game is 👍, it's just that you need to show us how to do some dribbles and skills
40                    game anj, pencarian lawan nya ga setara bbi rating tim gw 3035 ketemu lawan nya 3197 anj udah juga smart assist nya dongo bbi gw shooting udah pas tiang dekat malah nendang nya ketilang jauh anj jadinya ga gol apa lagi gara gara smart assist pemainku jadi lama nendang nya. mohon segera perbaiki lah konami soal pencarian lawan dan smart assist nya
41                                                                                                                                                                                                                                                                                                                                        efootball is the best unlike fc mobile .
42                                                                                                                                                                                                                                                                                                                                                           you want to reduce gb
43                                                                                                                                                                                                                                                                                                                                                                        so fun 😊
44                                                                                                                                                                                                                                                                                                                                                                  very nice game
45                                                                                                                                         hey konami, please fix lagging issues while playing pvp/division. i encountered many lagging even though i'm using wifi already. please fix your server asap. i'm done with this game if you guys aren't doing well with server issues.
46                                                                                                                                                                                                                                                                                                                                                                       very nice
47                                                                                                                                                                                                                                                                                                                                                                  best game ever
48                                                                                                                                                                                                                                                                                                                                                                            best
49                                                                                                                                                                                                                                                                                                               this game is so nice 🙂👍 i can take a hole day playing this game 🎮
Name: content_clean, dtype: object

In [59]:
df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3024\4156829393.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

0                                                                                                                                                                                                                                                                                                                                       good but i need ronaldo  nymar
1                                                                                                                                                                                                                                                                                                                                      it is better then the fc mobile
2                                                                                                                                                                                                                                                                                                                                  i think ronaldo 110 should now come
3                                                                                                                                                                                                                                                                                                                                                      best experience
4                                                                                                                                                                                                                                                                                                                                evrithing all so good game my opinion
5                                                                                                                                   i love the game it make me happy but one issues is when i want to use my coins to spin player they always give me the the wrong player and i am from japan i was born in japan konami please give me good players that when i spin
6                                                                                                                                                                                                                                                                                                                                                           scam packs
7                                                                                                                                                                                                                                                            stupid gamesomeone using cheatso stupid please update your system bro stupi bro stupid so so so so stupid
8                                                                                                                                                                                                                                                                                                                                                 all i can say is wow
9                                                                                                                                                                                                                                                                                                        game is good but to play in infinix have poor vissión graphic
10                                                                                                                                                                                                                                                                   this game was excellent record but some things are disturbing like the unstable server game glicz
11                                                                                                                                                                                                                                                           im giving 0 rating this game because i cant play this game in my device poco c31 64gb ram please fix that
12                                                                                                                                                                                                                                                                                                                                              is ok just try and see
13                                                                                                                                                                                                                                                                                                                       konami bokachoda rendir chele from bangladesh
14                                                                                                                                                                                                                                                                                           konami tor ma ke chudi sala suorer bacha tor make ulto kore from pakistan
15                                                                                                                                                                                                                                                                                                                                                     super efootball
16                                                                                                                                                                                                                                                                                                                                                          e football
17                                                                                                                                                                                                                                                                           very good game yayayayaya i like it its enjoyable wow majedaar majhdaar lalaalalalalalaal
18                                                                                                                                                                                                                                                                                                                                                          nice game
19                                                                                                                                                                                                                                                                                                                                                             love it
20                                                                                                                                                                                                              sincerely speaking  konami remove smart assist from your game  simply the game promotes cheating in matches with opponents not playing fair and square
21    this game has become completely paytowin for almost 11 months never received a single epic or big time card while paid players easily build top squads old epic cards were even downgraded which feels unfair and disrespectful weekly rewards are too low to matter and gameplay often feels scripted skill no longer mattersonly money does very disappointing
22                                                                                                                                                                                                                                                                                                                 the game is good but the server is having a problem
23                                                                                                                                                                                                                                                                                                                                             love you too sweetheart
24                                                                                                                                                                                                                                                                                                                                                           freestyle
25                                                                                                                                                                                                                                                                                                                                                        this is nice
26                                                                                                                                                                                                                                                                                         i hated this app because i tried to download it when it reaches 80 it stops
27                                                                                                                                                                                                                                                                                                                                                    just so perfect
28                                                                                                                                                                                                                                                                                                                                       voice ko on karna update karo
29                                                                                                                                                                                                                                                                                                                                       supporting ai not the players
30                                                                                                                                                                                                                                                                                                            ive been playing this game for 4 years now this game is
31                                                                                                                                                                                                                                                                                                                             a good experience with e footballtry it
32                                                                                                                                                                                                                                                                                      it is a good game with brilliant graphics i really love  the game very much it
33                                                                                                                                                                                                                                                                                                   this is wondorful and exelent most topast football game the world
34                                                                                                                                                                                                                                                                                                                                                                good
35                                                                                                                                                                                                                                                                                                                    cabdiqadir rooblr maxamuus marexan colow shamake
36                                                                                                                                                                                                                                                                                                                                                          game rusak
37                                                                                                                                                                                                                                                                                                      نريد نسخة لايت للهواتف الضعيفة و ما يحدث في division غير مقبول
38                                                                                                                                                                                                                                                                                                               why always unfinished game when i play with my friend
39                                                                                                                                                                                                                                                                            its a good game is  its just that you need to show us how to do some dribbles and skills
40          game anj pencarian lawan nya ga setara bbi rating tim gw 3035 ketemu lawan nya 3197 anj udah juga smart assist nya dongo bbi gw shooting udah pas tiang dekat malah nendang nya ketilang jauh anj jadinya ga gol apa lagi gara gara smart assist pemainku jadi lama nendang nya mohon segera perbaiki lah konami soal pencarian lawan dan smart assist nya
41                                                                                                                                                                                                                                                                                                                             efootball is the best unlike fc mobile
42                                                                                                                                                                                                                                                                                                                                               you want to reduce gb
43                                                                                                                                                                                                                                                                                                                                                             so fun
44                                                                                                                                                                                                                                                                                                                                                      very nice game
45                                                                                                                                      hey konami please fix lagging issues while playing pvpdivision i encountered many lagging even though im using wifi already please fix your server asap im done with this game if you guys arent doing well with server issues
46                                                                                                                                                                                                                                                                                                                                                           very nice
47                                                                                                                                                                                                                                                                                                                                                      best game ever
48                                                                                                                                                                                                                                                                                                                                                                best
49                                                                                                                                                                                                                                                                                                      this game is so nice  i can take a hole day playing this game
Name: content_clean, dtype: object

In [60]:
df['content_clean'].str.replace('[^\w\s]','',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3024\3208373244.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True)

0                                                                             good but i need ronaldo  nymar
1                                                                            it is better then the fc mobile
2                                                                        i think ronaldo 110 should now come
3                                                                                            best experience
4                                                                      evrithing all so good game my opinion
                                                       ...
95                                                                                              nice to play
96    efootball company work on this issue for us for the goalkeeper it must be cleaansheet not goals please
97                      efootball is the fastest and smoothest football game ever and it is also play simply
98                                                                                        indeed one of the
99                                  this game is scripted dont play this game this game is too bad fc better
Name: content_clean, Length: 100, dtype: object

In [61]:
def clean_data(text,column_name):
    df['content_clean'] = df[column_name].str.lower()
    df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)
    return df

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3024\1186799193.py:3: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)

In [62]:
df = clean_data(df, 'content')

print(df[['content', 'content_clean']])

                                                                                                        content  \
0                                                                   Good But........... I Need Ronaldo & Nymar🥲
1                                                                               it is better then the fc mobile
2                                                                           I think Ronaldo 110 should now come
3                                                                                               best experience
4                                                                         evrithing all so good game my opinion
..                                                                                                          ...
95                                                                                                 nice to play
96  Efootball company, work on this issue for us. For the goalkeeper, it must be cleaansheet, not goals, please
97                         eFootball is the fastest and smoothest football game ever and it is also play simply
98                                                                                          indeed one of the 👌
99                                    this game is scripted don't play this game this game is too bad fc better

                                                                                             content_clean
0                                                                           good but i need ronaldo  nymar
1                                                                          it is better then the fc mobile
2                                                                      i think ronaldo 110 should now come
3                                                                                          best experience
4                                                                    evrithing all so good game my opinion
..                                                                                                     ...
95                                                                                            nice to play
96  efootball company work on this issue for us for the goalkeeper it must be cleaansheet not goals please
97                    efootball is the fastest and smoothest football game ever and it is also play simply
98                                                                                      indeed one of the
99                                this game is scripted dont play this game this game is too bad fc better

[100 rows x 2 columns]

In [64]:
!pip install spacy

Collecting spacy
  Downloading spacy-3.8.11-cp313-cp313-win_amd64.whl.metadata (28 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp313-cp313-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.12-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.10-cp313-cp313-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.2-cp313-cp313-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.4.2 (from spacy)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typer-slim<1.0.0,>=0.3.0 (from spacy)
  Downloading typer_slim-0.24.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.3.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from spacy) (2.32.3)
Collecting pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 (from spacy)
  Downloading pydantic-2.12.5-py3-none-any.whl.metadata (90 kB)
Requirement already satisfied: jinja2 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from spacy) (25.0)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.41.5 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading pydantic_core-2.41.5-cp313-cp313-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Collecting typing-inspection>=0.4.2 (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2024.12.14)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.3.3-cp313-cp313-win_amd64.whl.metadata (7.7 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Collecting typer>=0.24.0 (from typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Collecting smart-open<8.0.0,>=5.2.1 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading smart_open-7.5.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: wrapt in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)
Requirement already satisfied: click>=8.2.1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Collecting shellingham>=1.3.0 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=12.3.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (14.2.0)
Collecting annotated-doc>=0.0.2 (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\lenovo\appdata\roaming\python\python313\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\lenovo\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Downloading spacy-3.8.11-cp313-cp313-win_amd64.whl (14.2 MB)
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   -------------- ------------------------- 5.0/14.2 MB 25.0 MB/s eta 0:00:01
   ----------------------------------- ---- 12.6/14.2 MB 30.4 MB/s eta 0:00:01
   ---------------------------------------- 14.2/14.2 MB 26.7 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.13-cp313-cp313-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp313-cp313-win_amd64.whl (25 kB)
Downloading preshed-3.0.12-cp313-cp313-win_amd64.whl (117 kB)
Downloading pydantic-2.12.5-py3-none-any.whl (463 kB)
Downloading pydantic_core-2.41.5-cp313-cp313-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 17.4 MB/s eta 0:00:00
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.2-cp313-cp313-win_amd64.whl (653 kB)
   ---------------------------------------- 0.0/653.1 kB ? eta -:--:--
   ---------------------------------------- 653.1/653.1 kB 4.8 MB/s eta 0:00:00
Downloading thinc-8.3.10-cp313-cp313-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 11.8 MB/s eta 0:00:00
Downloading typer_slim-0.24.0-py3-none-any.whl (3.4 kB)
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading blis-1.3.3-cp313-cp313-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ------------------------------------- -- 5.8/6.2 MB 27.6 MB/s eta 0:00:01
   ---------------------------------------- 6.2/6.2 MB 22.0 MB/s eta 0:00:00
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Downloading smart_open-7.5.1-py3-none-any.whl (64 kB)
Downloading typer-0.24.1-py3-none-any.whl (56 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: wasabi, typing-inspection, spacy-loggers, spacy-legacy, smart-open, shellingham, pydantic-core, murmurhash, cymem, cloudpathlib, catalogue, blis, annotated-types, annotated-doc, srsly, pydantic, preshed, typer, confection, typer-slim, thinc, weasel, spacy
Successfully installed annotated-doc-0.0.4 annotated-types-0.7.0 blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.23.0 confection-0.1.5 cymem-2.0.13 murmurhash-1.0.15 preshed-3.0.12 pydantic-2.12.5 pydantic-core-2.41.5 shellingham-1.5.4 smart-open-7.5.1 spacy-3.8.11 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.2 thinc-8.3.10 typer-0.24.1 typer-slim-0.24.0 typing-inspection-0.4.2 wasabi-1.1.3 weasel-0.4.3

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [65]:
#import library spacy
import spacy

In [67]:
# make sure the spaCy English model is installed
!python -m spacy download en_core_web_sm

# load model spacy untuk text processing
nlp = spacy.load('en_core_web_sm')
phrase = df.loc[1, 'content_clean']
phrase

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     --------- ------------------------------ 2.9/12.8 MB 18.2 MB/s eta 0:00:01
     ------------------------ --------------- 7.9/12.8 MB 21.8 MB/s eta 0:00:01
     ------------------------------------- - 12.3/12.8 MB 21.5 MB/s eta 0:00:01
     --------------------------------------- 12.8/12.8 MB 18.6 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

'it is better then the fc mobile'

In [68]:
doc = nlp(phrase)
doc

it is better then the fc mobile

In [69]:
[token for token in doc]

[it, is, better, then, the, fc, mobile]

In [70]:
[token.lemma_ for token in doc if not token.is_stop]

['well', 'fc', 'mobile']

In [71]:
list(nlp.Defaults.stop_words)[:100]

['empty',
 'amount',
 'themselves',
 'but',
 'further',
 'herein',
 'rather',
 'after',
 'myself',
 'along',
 'name',
 'too',
 'twenty',
 'whereupon',
 'it',
 'thereupon',
 'everywhere',
 'out',
 'nevertheless',
 're',
 'without',
 'are',
 'both',
 'before',
 'whereby',
 'moreover',
 'becomes',
 'yourself',
 'either',
 'become',
 'from',
 'she',
 'anyway',
 'they',
 'seeming',
 'two',
 'within',
 'during',
 'toward',
 'regarding',
 'every',
 'former',
 'same',
 'else',
 'per',
 'give',
 'move',
 'all',
 'behind',
 'am',
 'somehow',
 'thence',
 'serious',
 'whereas',
 '’ve',
 'somewhere',
 'nor',
 'here',
 "'d",
 'since',
 'her',
 'beforehand',
 'an',
 'could',
 'now',
 '‘ve',
 'should',
 'eleven',
 'whatever',
 'keep',
 'whom',
 'always',
 'as',
 'forty',
 'often',
 'ourselves',
 'hereafter',
 'third',
 'would',
 'until',
 'each',
 'though',
 'around',
 'sometime',
 'upon',
 'do',
 'yours',
 'take',
 'for',
 'hereby',
 'own',
 'eight',
 'just',
 'across',
 'does',
 'were',
 'any',
 'nobody',
 'latterly',
 'used']